In [1]:
import os
import pandas as pd 
import cv2
import json 


def read_json(fname):
    with open(fname, 'r') as f:
        return json.load(f)
    
def save_json(fname, data):
    with open(fname, 'w') as f:
        json.dump(data, f)
    return

In [2]:
def get_label_gloss_mappings(df):
    """
    Creates two dictionaries:
    - label_to_gloss: maps label index to gloss name
    - gloss_to_label: maps gloss name to label index

    Args:
        df (pd.DataFrame): DataFrame with 'gloss' and 'label' columns.

    Returns:
        dict, dict: (label_to_gloss, gloss_to_label)
    """
    label_to_gloss = dict(df[['label', 'Gloss']].drop_duplicates().sort_values('label').values)
    gloss_to_label = dict(df[['Gloss', 'label']].drop_duplicates().sort_values('label').values)
    return label_to_gloss, gloss_to_label

In [3]:
dataset_root = os.path.join('datasets', 'ASL-Citizen')
ttv = ['train.csv', 'test.csv', 'val.csv']
train, test, val = [pd.read_csv(os.path.join(dataset_root, i)) for i in ttv]

In [4]:
test.head()

,Participant ID,Video file,Gloss,ASL-LEX Code,label,fpath,prep_fpath,kpts_fpath
0,P48,46041911247233713-HAMMER.mp4,HAMMER,C_02_021,56,datasets\ASL-Citizen\top100_videos\46041911247...,datasets\ASL-Citizen\preprocess_videos\4604191...,datasets\ASL-Citizen\keypoints\460419112472337...
1,P7,014770041748456197-MOVIE.mp4,MOVIE,B_03_077,64,datasets\ASL-Citizen\top100_videos\01477004174...,datasets\ASL-Citizen\preprocess_videos\0147700...,datasets\ASL-Citizen\keypoints\014770041748456...
2,P42,8372181221997397-SERVE 1.mp4,SERVE,E_02_004,76,datasets\ASL-Citizen\top100_videos\83721812219...,datasets\ASL-Citizen\preprocess_videos\8372181...,datasets\ASL-Citizen\keypoints\837218122199739...
3,P29,6422461467297818-CIGARETTE.mp4,CIGARETTE,C_01_059,31,datasets\ASL-Citizen\top100_videos\64224614672...,datasets\ASL-Citizen\preprocess_videos\6422461...,datasets\ASL-Citizen\keypoints\642246146729781...
4,P18,04600046798432267-THAT.mp4,THAT,C_03_059,94,datasets\ASL-Citizen\top100_videos\04600046798...,datasets\ASL-Citizen\preprocess_videos\0460004...,datasets\ASL-Citizen\keypoints\046000467984322...

In [5]:
from data_loader import MSASLKeypointsDataset16Frames

In [6]:
l_to_g,_ = get_label_gloss_mappings(train)
save_json('class_mapper.json', l_to_g)

In [7]:
get_fname = lambda x: os.path.basename(x).split('.')[0]
add_ext = lambda x, ext = '.json': x + ext

train_fnames = train['fpath'].apply(get_fname).apply(add_ext)
val_fnames = val['fpath'].apply(get_fname).apply(add_ext)
test_fnames = test['fpath'].apply(get_fname).apply(add_ext)
root_dir = os.path.join(dataset_root, 'top100_videos_16frames_kpts')

In [8]:
train_ds = MSASLKeypointsDataset16Frames(
    root_dir,
    train_fnames,
    train.label.to_list()
    )

valid_ds = MSASLKeypointsDataset16Frames(
    root_dir,
    val_fnames,
    val.label.to_list()
)

test_ds = MSASLKeypointsDataset16Frames(
    root_dir,
    test_fnames,
    test.label.to_list()
)

In [9]:
train_ds[0][0].shape

torch.Size([16, 144])

In [10]:
import torch
from torch.utils.data import DataLoader
from fastai.data.core import DataLoaders
from fastai.callback.tensorboard import TensorBoardCallback
from fastai.callback.tracker import SaveModelCallback, EarlyStoppingCallback
from fastai.callback.training import GradientClip
from models import GRUModel, LSTMModel, CNNRNN, BiGRUWithSeq
from fastai.learner import Learner
from fastai.metrics import accuracy, top_k_accuracy, F1ScoreMulti
from fastai.losses import CrossEntropyLossFlat
from sklearn.metrics import f1_score


def f1_score_flat(preds, targs, average='macro'):
    preds = preds.argmax(dim=1).cpu().numpy()  # Convert from logits to predicted classes
    targs = targs.cpu().numpy()                # Ensure targets are numpy arrays
    print(preds)
    print(targs)
    return f1_score(targs, preds, average=average)

In [19]:
get_available_device_name = lambda learn : next(learn.model.parameters()).device
get_available_dtype = lambda learn : next(learn.model.parameters()).dtype

def create_loggers(model_name):
    """
    Creates TensorBoard and model save callbacks for logging.

    Args:
        model_name (str): Name of the model.

    Returns:
        TensorBoardCallback, SaveModelCallback: Callbacks for logging.
    """
    log_dir = os.path.join('logs', model_name)
    os.makedirs('models', exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)
    tb_logger = TensorBoardCallback(log_dir=log_dir, trace_model=False, log_preds=False)
    save_model = SaveModelCallback(monitor='valid_loss', fname=model_name, with_opt=True)
    return tb_logger, save_model

def create_fast_trainer(model: torch.nn.Module, train_ds, valid_ds, model_name, batch_size = 64, verbose = True, additional_cbs = [], load_saved_model = True):
    tb_logger, save_model = create_loggers(model_name)
    dls = DataLoaders.from_dsets(train_ds, valid_ds, bs=batch_size, shuffle_train=True)
    cbs = [tb_logger, save_model] + additional_cbs
    learner = Learner(
        dls.cuda(),  
        model.cuda(),
        loss_func=CrossEntropyLossFlat(),
        metrics=[accuracy, top_k_accuracy],
        cbs=cbs, 
        wd=1e-2
    ).to_fp16()

    torch.backends.cuda.matmul.allow_tf32 = True
    learner.create_opt()

    if verbose:
        try:
            print(learner.summary())
        except Exception as e:
            print(f"Error in summary: {e}")
        print(get_available_device_name(learner))
        print(get_available_dtype(learner))  # Should show torch.float32
        print(learner.opt)  # Should show "MixedPrecision" in callback list
        print(learner.dls.device)
        print(dls.one_batch()[0].device)

    if f'{model_name}.pth' in os.listdir('models') and load_saved_model:
        print(f"Found model {model_name} in the models directory.")
        choice = input("Load the model from the directory ? (y/n) : ")
        if choice == 'y':
            learner.load(model_name, with_opt=True)

    return learner

def train_model(learner : Learner, epochs, lr_max = 1e-3, pct_start = 0.2):
    learner.fit_one_cycle(epochs, lr_max=lr_max, pct_start= pct_start)
    return learner

lbl_to_gloss,_ = get_label_gloss_mappings(train)
def get_predictions(learner, test_ds = None):
    """
    Get predictions from the model.

    Args:
        learner (Learner): The trained model.
        test_ds (Dataset, optional): Test dataset. Defaults to None.

    Returns:
        list: List of predictions.
    """
    if test_ds is None:
        test_dl = learner.dls.test_dl(test_ds, shuffle=False)
        preds, true = learner.get_preds(dl=test_dl)
    else:
        preds, true = learner.get_preds()
    p, t = torch.argmax(preds, dim=1).tolist(), true.tolist()
    inference = pd.DataFrame({'pred': p, 'true': t})
    inference['pred_class'] = inference['pred'].map(lbl_to_gloss)
    inference['true_class'] = inference['true'].map(lbl_to_gloss)
    inference['correct'] = inference['pred'] == inference['true']
    return inference

def tp_fp_classification_report(inference, class_index, return_metrics = False):
    total = inference[inference['true'] == class_index].shape[0]
    tp = inference[(inference['pred'] == class_index) & (inference['true'] == class_index)].shape[0]
    fp = inference[(inference['pred'] == class_index) & (inference['true'] != class_index)].shape[0]
    if return_metrics:
        return total, tp/total, fp/total
    print(f" Clf Report for {lbl_to_gloss[class_index]} ({class_index}) ".center(60, '='))
    print(f"True Positives: {tp}/{total} => {tp/total:.1%}")
    print(f"False Positives: {fp}/{total} => {fp/total:.1%}")

In [12]:
from sklearn.model_selection import GroupKFold
from torch.utils.data import Subset
import numpy as np

In [13]:
def cross_validate_pipeline(
    full_dataset,
    labels,
    groups,
    model_cls,
    model_kwargs,
    n_splits=5,
    batch_size=64,
    epochs=10,
    lr_max=1e-2,
    pct_start=0.2,
    verbose=True
):
    """
    Performs group-aware K-fold cross-validation using FastAI.

    Args:
        full_dataset (Dataset): The complete PyTorch Dataset.
        labels (List[int]): Class labels aligned with full_dataset.
        groups (List): Group identifiers (e.g., contributor_id) aligned with full_dataset.
        model_cls (Callable): Class or factory returning a fresh model instance.
        model_kwargs (dict): kwargs to pass when instantiating the model per fold.
        n_splits (int): Number of folds.
        batch_size (int): Batch size for training.
        epochs (int): Number of epochs per fold.
        lr_max (float): Max learning rate for fit_one_cycle.
        pct_start (float): pct_start for fit_one_cycle.
        verbose (bool): Whether to print fold summaries.

    Returns:
        pd.DataFrame: DataFrame with per-fold metrics (accuracy, top-5) and aggregated mean/std.
    """
    gkf = GroupKFold(n_splits=n_splits)
    results = []
    indexes  = []
    best_acs = (None, 0)

    for fold, (train_idx, valid_idx) in enumerate(
        gkf.split(X=np.zeros(len(groups)), y=labels, groups=groups)
    ):
        fold_name = f"fold_{fold+1}"
        if verbose: print(f"\n=== Starting {fold_name} ===")

        # Subset datasets
        train_subsets = full_dataset.iloc[train_idx].reset_index(drop=True)
        valid_subsets = full_dataset.iloc[valid_idx].reset_index(drop=True)

        train_fnames = train_subsets['fpath'].apply(get_fname).apply(add_ext)
        val_fnames = valid_subsets['fpath'].apply(get_fname).apply(add_ext)

        train_ds = MSASLKeypointsDataset16Frames(root_dir, train_fnames, train_subsets.label.to_list())
        valid_ds = MSASLKeypointsDataset16Frames(root_dir, val_fnames, valid_subsets.label.to_list())
        # Instantiate fresh model
        model = model_cls(**model_kwargs)

        # Create FastAI learner
        learner = create_fast_trainer(
            model=model,
            train_ds=train_ds,
            valid_ds=valid_ds,
            model_name=fold_name,
            batch_size=batch_size,
            verbose=verbose,
            additional_cbs=[GradientClip(0.1), EarlyStoppingCallback(monitor='valid_loss', patience=10)],
            load_saved_model=False
        )

        # Train
        learner = train_model(learner, epochs=epochs, lr_max=lr_max, pct_start=pct_start)

        # Evaluate on validation set
        preds, targs = learner.get_preds(dl=learner.dls.valid)
        acc1 = accuracy(preds, targs).item()
        acc5 = top_k_accuracy(preds, targs, k=5).item()

        if verbose:
            print(f"{fold_name} — Acc@1: {acc1:.4f}, Acc@5: {acc5:.4f}")

        results.append({
            "fold": fold+1,
            "acc1": acc1,
            "acc5": acc5
        })

        indexes.append((fold_name, train_idx, valid_idx))
        if acc1 > best_acs[1]:
            best_acs = [fold_name, acc1]

        torch.cuda.empty_cache()

    # Aggregate
    df = pd.DataFrame(results)
    summary = {
        "fold": "mean/std",
        "acc1": f"{df.acc1.mean():.4f} ± {df.acc1.std():.4f}",
        "acc5": f"{df.acc5.mean():.4f} ± {df.acc5.std():.4f}"
    }
    print(f"\nBest fold: {best_acs[0]} with Acc@1: {best_acs[1]:.4f}") if verbose else None
    return df, summary, indexes

In [14]:
cnn_kwargs = {
    'out_channels': 128,
    'kernel_size': 3,
    'dropout': 0.1,
    'use_pooling': True
}

rnn_kwargs = {
    'num_layers': 1,
    'dropout': 0.2,
    'bidirectional': True,
}

RNN_HIDDEN_SIZE = 256

INPUT_SIZE = 144
NUM_CLASSES = 100
EPOCHS = 100
BATCH_SIZE = 64
LR_MAX = 1e-3
VERBOSE = True

In [15]:
gru_model = GRUModel(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, rnn_hidden_size=RNN_HIDDEN_SIZE, kwargs={'rnn_kwargs': rnn_kwargs}) # baseline model
lstm_model = LSTMModel(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, rnn_hidden_size=RNN_HIDDEN_SIZE, kwargs={'rnn_kwargs': rnn_kwargs})
cnn_gru = CNNRNN(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, num_cnn_blocks=1, use_lstm=False, rnn_hidden_size=RNN_HIDDEN_SIZE, 
                kwargs={'cnn_kwargs': cnn_kwargs, 'rnn_kwargs': rnn_kwargs})
cnn_lstm = CNNRNN(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, num_cnn_blocks=1, use_lstm=True,  rnn_hidden_size=RNN_HIDDEN_SIZE, 
                kwargs={'cnn_kwargs': cnn_kwargs, 'rnn_kwargs': rnn_kwargs})
gru_seq = BiGRUWithSeq(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, num_layers=2)

In [57]:
models = [
    ('gru_baseline', gru_model),
    ('lstm_baseline', lstm_model),
    ('cnn_gru', cnn_gru),
    ('cnn_lstm', cnn_lstm),
    ('bi_gru_seq', gru_seq)
]
Learners = []
inferences = []
for model_name, model in models:
    print(f" {model_name} ".center(60, '='))
    learner = create_fast_trainer(model, train_ds, valid_ds, model_name, batch_size=BATCH_SIZE, verbose=VERBOSE)
    learner = train_model(learner, EPOCHS, lr_max=LR_MAX)
    inference = get_predictions(learner, test_ds)
    Learners.append((model_name, learner))
    inferences.append((model_name, inference))
    print()

======================= gru_baseline =======================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'GRUModel' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD11630F10>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.60671854019165.
Better model found at epoch 1 with valid_loss value: 4.605711460113525.
Better model found at epoch 2 with valid_loss value: 4.604403495788574.
Better model found at epoch 3 with valid_loss value: 4.602372169494629.
Better model found at epoch 4 with valid_loss value: 4.598360061645508.
Better model found at epoch 5 with valid_loss value: 4.574693202972412.
Better model found at epoch 6 with valid_loss value: 4.446888446807861.
Better model found at epoch 7 with valid_loss value: 4.35939884185791.
Better model found at epoch 8 with valid_loss value: 4.320028305053711.
Better model found at epoch 9 with valid_loss value: 4.295571327209473.
Better model found at epoch 10 with valid_loss value: 4.256669521331787.
Better model found at epoch 11 with valid_loss value: 4.204994201660156.
Better model found at epoch 12 with valid_loss value: 4.140260219573975.
Better model found at epoch 13 with valid_loss value: 4.093429088592529.
Better model found at epoch 14 with valid_loss value: 4.036839962005615.
Better model found at epoch 15 with valid_loss value: 3.974569320678711.
Better model found at epoch 16 with valid_loss value: 3.9421722888946533.
Better model found at epoch 17 with valid_loss value: 3.8559696674346924.
Better model found at epoch 18 with valid_loss value: 3.819803237915039.
Better model found at epoch 19 with valid_loss value: 3.771461248397827.
Better model found at epoch 20 with valid_loss value: 3.7244226932525635.
Better model found at epoch 21 with valid_loss value: 3.649507761001587.
Better model found at epoch 22 with valid_loss value: 3.6123337745666504.
Better model found at epoch 23 with valid_loss value: 3.5821611881256104.
Better model found at epoch 24 with valid_loss value: 3.5270862579345703.
Better model found at epoch 25 with valid_loss value: 3.514861822128296.
Better model found at epoch 26 with valid_loss value: 3.4589738845825195.
Better model found at epoch 27 with valid_loss value: 3.417797565460205.
Better model found at epoch 28 with valid_loss value: 3.37988543510437.
Better model found at epoch 29 with valid_loss value: 3.364691972732544.
Better model found at epoch 30 with valid_loss value: 3.354372262954712.
Better model found at epoch 31 with valid_loss value: 3.3208186626434326.
Better model found at epoch 32 with valid_loss value: 3.251086950302124.
Better model found at epoch 33 with valid_loss value: 3.232905387878418.
Better model found at epoch 34 with valid_loss value: 3.2202680110931396.
Better model found at epoch 35 with valid_loss value: 3.205230474472046.
Better model found at epoch 36 with valid_loss value: 3.187246322631836.
Better model found at epoch 37 with valid_loss value: 3.1469244956970215.
Better model found at epoch 39 with valid_loss value: 3.08274507522583.
Better model found at epoch 42 with valid_loss value: 3.040085554122925.
Better model found at epoch 44 with valid_loss value: 2.997288465499878.
Better model found at epoch 46 with valid_loss value: 2.9911439418792725.
Better model found at epoch 48 with valid_loss value: 2.9510200023651123.
Better model found at epoch 49 with valid_loss value: 2.945988655090332.
Better model found at epoch 50 with valid_loss value: 2.919400691986084.
Better model found at epoch 52 with valid_loss value: 2.9027109146118164.
Better model found at epoch 53 with valid_loss value: 2.887871503829956.
Better model found at epoch 54 with valid_loss value: 2.887350082397461.
Better model found at epoch 56 with valid_loss value: 2.8703911304473877.
Better model found at epoch 57 with valid_loss value: 2.853449583053589.
Better model found at epoch 59 with valid_loss value: 2.8196849822998047.
Better model found at epoch 60 with valid_loss value: 2.816202163696289.
Better model found at epoch 62 with valid_loss value: 2.810925006866455.
Better model found at epoch 63 with valid_loss value: 2.7962327003479004.
Better model found at epoch 66 with valid_loss value: 2.78694748878479.
Better model found at epoch 67 with valid_loss value: 2.786266803741455.
Better model found at epoch 68 with valid_loss value: 2.7816412448883057.
Better model found at epoch 69 with valid_loss value: 2.7751336097717285.
Better model found at epoch 70 with valid_loss value: 2.755192518234253.
Better model found at epoch 76 with valid_loss value: 2.743054151535034.
Better model found at epoch 77 with valid_loss value: 2.7409231662750244.
Better model found at epoch 81 with valid_loss value: 2.7380640506744385.
Better model found at epoch 82 with valid_loss value: 2.724998712539673.
Better model found at epoch 94 with valid_loss value: 2.7242915630340576.

====================== lstm_baseline =======================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'LSTMModel' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD138A40D0>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.608165264129639.
Better model found at epoch 1 with valid_loss value: 4.60771369934082.
Better model found at epoch 2 with valid_loss value: 4.607104301452637.
Better model found at epoch 3 with valid_loss value: 4.606067657470703.
Better model found at epoch 4 with valid_loss value: 4.603183746337891.
Better model found at epoch 5 with valid_loss value: 4.560542583465576.
Better model found at epoch 6 with valid_loss value: 4.465068340301514.
Better model found at epoch 7 with valid_loss value: 4.389425754547119.
Better model found at epoch 8 with valid_loss value: 4.325656890869141.
Better model found at epoch 9 with valid_loss value: 4.272026538848877.
Better model found at epoch 10 with valid_loss value: 4.210241794586182.
Better model found at epoch 11 with valid_loss value: 4.182412147521973.
Better model found at epoch 12 with valid_loss value: 4.146559238433838.
Better model found at epoch 13 with valid_loss value: 4.092617034912109.
Better model found at epoch 14 with valid_loss value: 4.026493072509766.
Better model found at epoch 15 with valid_loss value: 3.9627349376678467.
Better model found at epoch 16 with valid_loss value: 3.9042108058929443.
Better model found at epoch 17 with valid_loss value: 3.8545308113098145.
Better model found at epoch 18 with valid_loss value: 3.8187711238861084.
Better model found at epoch 19 with valid_loss value: 3.717080593109131.
Better model found at epoch 21 with valid_loss value: 3.61370587348938.
Better model found at epoch 22 with valid_loss value: 3.5989654064178467.
Better model found at epoch 23 with valid_loss value: 3.5763957500457764.
Better model found at epoch 24 with valid_loss value: 3.542142391204834.
Better model found at epoch 25 with valid_loss value: 3.5333895683288574.
Better model found at epoch 26 with valid_loss value: 3.4258131980895996.
Better model found at epoch 27 with valid_loss value: 3.3381853103637695.
Better model found at epoch 28 with valid_loss value: 3.3193349838256836.
Better model found at epoch 29 with valid_loss value: 3.3073623180389404.
Better model found at epoch 30 with valid_loss value: 3.2394468784332275.
Better model found at epoch 31 with valid_loss value: 3.213623046875.
Better model found at epoch 33 with valid_loss value: 3.101043939590454.
Better model found at epoch 36 with valid_loss value: 3.066991090774536.
Better model found at epoch 37 with valid_loss value: 3.005504608154297.
Better model found at epoch 38 with valid_loss value: 2.9887590408325195.
Better model found at epoch 39 with valid_loss value: 2.9480412006378174.
Better model found at epoch 40 with valid_loss value: 2.905041456222534.
Better model found at epoch 41 with valid_loss value: 2.8946635723114014.
Better model found at epoch 43 with valid_loss value: 2.8228864669799805.
Better model found at epoch 45 with valid_loss value: 2.771669387817383.
Better model found at epoch 46 with valid_loss value: 2.734652280807495.
Better model found at epoch 48 with valid_loss value: 2.693735122680664.
Better model found at epoch 49 with valid_loss value: 2.647834539413452.
Better model found at epoch 52 with valid_loss value: 2.622049331665039.
Better model found at epoch 53 with valid_loss value: 2.5999319553375244.
Better model found at epoch 55 with valid_loss value: 2.5603718757629395.
Better model found at epoch 57 with valid_loss value: 2.556966781616211.
Better model found at epoch 58 with valid_loss value: 2.512892723083496.
Better model found at epoch 60 with valid_loss value: 2.4721240997314453.
Better model found at epoch 62 with valid_loss value: 2.456270694732666.
Better model found at epoch 63 with valid_loss value: 2.4372615814208984.
Better model found at epoch 65 with valid_loss value: 2.429255247116089.
Better model found at epoch 66 with valid_loss value: 2.417311906814575.
Better model found at epoch 67 with valid_loss value: 2.398876190185547.
Better model found at epoch 69 with valid_loss value: 2.353548288345337.
Better model found at epoch 71 with valid_loss value: 2.346367597579956.
Better model found at epoch 74 with valid_loss value: 2.3435184955596924.
Better model found at epoch 76 with valid_loss value: 2.3245959281921387.
Better model found at epoch 78 with valid_loss value: 2.298381805419922.
Better model found at epoch 79 with valid_loss value: 2.298001527786255.
Better model found at epoch 80 with valid_loss value: 2.2914230823516846.
Better model found at epoch 82 with valid_loss value: 2.281449317932129.
Better model found at epoch 84 with valid_loss value: 2.2782397270202637.
Better model found at epoch 88 with valid_loss value: 2.2730984687805176.
Better model found at epoch 96 with valid_loss value: 2.2720370292663574.

========================= cnn_gru ==========================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNRNN' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD13975F10>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.602174758911133.
Better model found at epoch 1 with valid_loss value: 4.588860511779785.
Better model found at epoch 2 with valid_loss value: 4.574275970458984.
Better model found at epoch 3 with valid_loss value: 4.549103736877441.
Better model found at epoch 4 with valid_loss value: 4.498546600341797.
Better model found at epoch 5 with valid_loss value: 4.4062981605529785.
Better model found at epoch 6 with valid_loss value: 4.296168327331543.
Better model found at epoch 7 with valid_loss value: 4.193922996520996.
Better model found at epoch 8 with valid_loss value: 4.092860698699951.
Better model found at epoch 9 with valid_loss value: 4.000340938568115.
Better model found at epoch 10 with valid_loss value: 3.8971359729766846.
Better model found at epoch 11 with valid_loss value: 3.8060691356658936.
Better model found at epoch 12 with valid_loss value: 3.71980357170105.
Better model found at epoch 13 with valid_loss value: 3.6328628063201904.
Better model found at epoch 14 with valid_loss value: 3.541642665863037.
Better model found at epoch 15 with valid_loss value: 3.489656686782837.
Better model found at epoch 16 with valid_loss value: 3.3971145153045654.
Better model found at epoch 17 with valid_loss value: 3.341613531112671.
Better model found at epoch 18 with valid_loss value: 3.291131019592285.
Better model found at epoch 19 with valid_loss value: 3.2373809814453125.
Better model found at epoch 20 with valid_loss value: 3.1677212715148926.
Better model found at epoch 21 with valid_loss value: 3.116489887237549.
Better model found at epoch 22 with valid_loss value: 3.082704544067383.
Better model found at epoch 23 with valid_loss value: 3.028759479522705.
Better model found at epoch 24 with valid_loss value: 2.986736536026001.
Better model found at epoch 25 with valid_loss value: 2.973459482192993.
Better model found at epoch 26 with valid_loss value: 2.90836238861084.
Better model found at epoch 28 with valid_loss value: 2.8817169666290283.
Better model found at epoch 29 with valid_loss value: 2.8673057556152344.
Better model found at epoch 30 with valid_loss value: 2.821798086166382.
Better model found at epoch 31 with valid_loss value: 2.812800884246826.
Better model found at epoch 32 with valid_loss value: 2.7604925632476807.
Better model found at epoch 34 with valid_loss value: 2.7430169582366943.
Better model found at epoch 35 with valid_loss value: 2.7379424571990967.
Better model found at epoch 36 with valid_loss value: 2.702836275100708.
Better model found at epoch 37 with valid_loss value: 2.700305223464966.
Better model found at epoch 38 with valid_loss value: 2.698695659637451.
Better model found at epoch 39 with valid_loss value: 2.6850714683532715.
Better model found at epoch 40 with valid_loss value: 2.6834678649902344.
Better model found at epoch 41 with valid_loss value: 2.638960599899292.
Better model found at epoch 42 with valid_loss value: 2.627490997314453.
Better model found at epoch 43 with valid_loss value: 2.6076879501342773.
Better model found at epoch 44 with valid_loss value: 2.6004419326782227.
Better model found at epoch 46 with valid_loss value: 2.5910112857818604.
Better model found at epoch 47 with valid_loss value: 2.589611530303955.
Better model found at epoch 48 with valid_loss value: 2.5892884731292725.
Better model found at epoch 51 with valid_loss value: 2.578306198120117.
Better model found at epoch 52 with valid_loss value: 2.5655601024627686.
Better model found at epoch 54 with valid_loss value: 2.5531835556030273.
Better model found at epoch 60 with valid_loss value: 2.53802227973938.
Better model found at epoch 62 with valid_loss value: 2.528153419494629.
Better model found at epoch 69 with valid_loss value: 2.5226380825042725.
Better model found at epoch 73 with valid_loss value: 2.514587640762329.
Better model found at epoch 84 with valid_loss value: 2.5143048763275146.
Better model found at epoch 88 with valid_loss value: 2.513319492340088.
Better model found at epoch 89 with valid_loss value: 2.5111522674560547.

========================= cnn_lstm =========================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNRNN' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD0F1C5AD0>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.604450225830078.
Better model found at epoch 1 with valid_loss value: 4.602069854736328.
Better model found at epoch 2 with valid_loss value: 4.596027851104736.
Better model found at epoch 3 with valid_loss value: 4.582094192504883.
Better model found at epoch 4 with valid_loss value: 4.544991970062256.
Better model found at epoch 5 with valid_loss value: 4.462834358215332.
Better model found at epoch 6 with valid_loss value: 4.358616352081299.
Better model found at epoch 7 with valid_loss value: 4.239348888397217.
Better model found at epoch 8 with valid_loss value: 4.127914905548096.
Better model found at epoch 9 with valid_loss value: 4.00471830368042.
Better model found at epoch 10 with valid_loss value: 3.920595169067383.
Better model found at epoch 11 with valid_loss value: 3.7903690338134766.
Better model found at epoch 12 with valid_loss value: 3.7309625148773193.
Better model found at epoch 13 with valid_loss value: 3.6200244426727295.
Better model found at epoch 14 with valid_loss value: 3.535318374633789.
Better model found at epoch 15 with valid_loss value: 3.477121114730835.
Better model found at epoch 16 with valid_loss value: 3.396002769470215.
Better model found at epoch 17 with valid_loss value: 3.317375659942627.
Better model found at epoch 18 with valid_loss value: 3.286020040512085.
Better model found at epoch 19 with valid_loss value: 3.2069997787475586.
Better model found at epoch 20 with valid_loss value: 3.1642372608184814.
Better model found at epoch 21 with valid_loss value: 3.12743878364563.
Better model found at epoch 22 with valid_loss value: 3.0633771419525146.
Better model found at epoch 23 with valid_loss value: 3.048617124557495.
Better model found at epoch 24 with valid_loss value: 2.9898951053619385.
Better model found at epoch 26 with valid_loss value: 2.972452402114868.
Better model found at epoch 27 with valid_loss value: 2.929908275604248.
Better model found at epoch 28 with valid_loss value: 2.8835999965667725.
Better model found at epoch 29 with valid_loss value: 2.8670880794525146.
Better model found at epoch 31 with valid_loss value: 2.8035242557525635.
Better model found at epoch 32 with valid_loss value: 2.7975053787231445.
Better model found at epoch 33 with valid_loss value: 2.7951438426971436.
Better model found at epoch 35 with valid_loss value: 2.765923261642456.
Better model found at epoch 36 with valid_loss value: 2.7104501724243164.
Better model found at epoch 38 with valid_loss value: 2.7066826820373535.
Better model found at epoch 40 with valid_loss value: 2.678682804107666.
Better model found at epoch 41 with valid_loss value: 2.6634087562561035.
Better model found at epoch 43 with valid_loss value: 2.645742177963257.
Better model found at epoch 44 with valid_loss value: 2.6311371326446533.
Better model found at epoch 46 with valid_loss value: 2.599004030227661.
Better model found at epoch 49 with valid_loss value: 2.598144292831421.
Better model found at epoch 50 with valid_loss value: 2.59348464012146.
Better model found at epoch 51 with valid_loss value: 2.575437068939209.
Better model found at epoch 52 with valid_loss value: 2.568232536315918.
Better model found at epoch 53 with valid_loss value: 2.5448946952819824.
Better model found at epoch 55 with valid_loss value: 2.540693998336792.
Better model found at epoch 60 with valid_loss value: 2.5281474590301514.
Better model found at epoch 61 with valid_loss value: 2.5273776054382324.
Better model found at epoch 63 with valid_loss value: 2.507201910018921.
Better model found at epoch 67 with valid_loss value: 2.5030813217163086.
Better model found at epoch 71 with valid_loss value: 2.489387273788452.
Better model found at epoch 88 with valid_loss value: 2.485952377319336.
Better model found at epoch 96 with valid_loss value: 2.484299659729004.
Better model found at epoch 98 with valid_loss value: 2.481602907180786.

======================== bi_gru_seq ========================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'BiGRUWithSeq' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD11460B90>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.607635498046875.
Better model found at epoch 1 with valid_loss value: 4.607481002807617.
Better model found at epoch 2 with valid_loss value: 4.607260704040527.
Better model found at epoch 3 with valid_loss value: 4.607045650482178.
Better model found at epoch 4 with valid_loss value: 4.60671329498291.
Better model found at epoch 5 with valid_loss value: 4.60589075088501.
Better model found at epoch 6 with valid_loss value: 4.601866245269775.
Better model found at epoch 7 with valid_loss value: 4.58761739730835.
Better model found at epoch 8 with valid_loss value: 4.579031467437744.
Better model found at epoch 9 with valid_loss value: 4.566543102264404.
Better model found at epoch 10 with valid_loss value: 4.56339693069458.
Better model found at epoch 11 with valid_loss value: 4.55875301361084.
Better model found at epoch 12 with valid_loss value: 4.553063869476318.
Better model found at epoch 13 with valid_loss value: 4.547448635101318.
Better model found at epoch 14 with valid_loss value: 4.544198989868164.
Better model found at epoch 15 with valid_loss value: 4.543849945068359.
Better model found at epoch 16 with valid_loss value: 4.538638114929199.
Better model found at epoch 17 with valid_loss value: 4.53376579284668.
Better model found at epoch 18 with valid_loss value: 4.528838634490967.
Better model found at epoch 19 with valid_loss value: 4.525669574737549.
Better model found at epoch 21 with valid_loss value: 4.517733573913574.
Better model found at epoch 22 with valid_loss value: 4.506872177124023.
Better model found at epoch 23 with valid_loss value: 4.495197296142578.
Better model found at epoch 24 with valid_loss value: 4.487104892730713.
Better model found at epoch 25 with valid_loss value: 4.47283935546875.
Better model found at epoch 26 with valid_loss value: 4.467813968658447.
Better model found at epoch 27 with valid_loss value: 4.464437961578369.
Better model found at epoch 28 with valid_loss value: 4.457888603210449.
Better model found at epoch 29 with valid_loss value: 4.445819854736328.
Better model found at epoch 30 with valid_loss value: 4.42752742767334.
Better model found at epoch 31 with valid_loss value: 4.426669120788574.
Better model found at epoch 32 with valid_loss value: 4.409695148468018.
Better model found at epoch 34 with valid_loss value: 4.401805400848389.
Better model found at epoch 35 with valid_loss value: 4.388584613800049.
Better model found at epoch 36 with valid_loss value: 4.380462646484375.
Better model found at epoch 37 with valid_loss value: 4.373281478881836.
Better model found at epoch 38 with valid_loss value: 4.365540504455566.
Better model found at epoch 40 with valid_loss value: 4.356991767883301.
Better model found at epoch 41 with valid_loss value: 4.34966516494751.
Better model found at epoch 42 with valid_loss value: 4.347183704376221.
Better model found at epoch 44 with valid_loss value: 4.337997913360596.
Better model found at epoch 45 with valid_loss value: 4.333572864532471.
Better model found at epoch 46 with valid_loss value: 4.3215436935424805.
Better model found at epoch 47 with valid_loss value: 4.321521282196045.
Better model found at epoch 48 with valid_loss value: 4.318062782287598.
Better model found at epoch 49 with valid_loss value: 4.316257953643799.
Better model found at epoch 50 with valid_loss value: 4.312010288238525.
Better model found at epoch 51 with valid_loss value: 4.302764415740967.
Better model found at epoch 52 with valid_loss value: 4.295382499694824.
Better model found at epoch 53 with valid_loss value: 4.289910793304443.
Better model found at epoch 54 with valid_loss value: 4.287582874298096.
Better model found at epoch 55 with valid_loss value: 4.286193370819092.
Better model found at epoch 56 with valid_loss value: 4.283693790435791.
Better model found at epoch 58 with valid_loss value: 4.282133102416992.
Better model found at epoch 59 with valid_loss value: 4.276700496673584.
Better model found at epoch 61 with valid_loss value: 4.267934322357178.
Better model found at epoch 63 with valid_loss value: 4.262537002563477.
Better model found at epoch 64 with valid_loss value: 4.253715991973877.
Better model found at epoch 66 with valid_loss value: 4.250931262969971.
Better model found at epoch 67 with valid_loss value: 4.23980712890625.
Better model found at epoch 68 with valid_loss value: 4.238269805908203.
Better model found at epoch 72 with valid_loss value: 4.236316680908203.
Better model found at epoch 73 with valid_loss value: 4.228473663330078.
Better model found at epoch 74 with valid_loss value: 4.227290153503418.
Better model found at epoch 76 with valid_loss value: 4.22568941116333.
Better model found at epoch 77 with valid_loss value: 4.220773220062256.
Better model found at epoch 80 with valid_loss value: 4.218595504760742.
Better model found at epoch 81 with valid_loss value: 4.2176690101623535.
Better model found at epoch 82 with valid_loss value: 4.217523097991943.
Better model found at epoch 83 with valid_loss value: 4.214816570281982.
Better model found at epoch 87 with valid_loss value: 4.214226245880127.
Better model found at epoch 88 with valid_loss value: 4.214042663574219.
Better model found at epoch 89 with valid_loss value: 4.211256504058838.
Better model found at epoch 95 with valid_loss value: 4.210718154907227.

The baseline model gave the highest accuracy of 48%

Validation

In [73]:
inf_fname = 'inference'
os.makedirs(inf_fname,exist_ok=True)

for model_name, i in inferences:
    i.to_csv(os.path.join(inf_fname, f'{model_name}.csv'), index=False)
    print(f"Saved inference for {model_name} to {os.path.join(inf_fname, f'{model_name}.csv')}")
    for ind in range(10):
        tp_fp_classification_report(i, ind)
    print()

Saved inference for gru_baseline to inference\gru_baseline.csv
================== Clf Report for AXE (0) ==================
True Positives: 2
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 1
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 2
False Positives: 1
================== Clf Report for BEE (3) ==================
True Positives: 1
False Positives: 10
================ Clf Report for BELIEVE (4) ================
True Positives: 1
False Positives: 0
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 2
================= Clf Report for BITE (6) ==================
True Positives: 0
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 2
False Positives: 3
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 2
================ Clf Report for BOTTLE (9) =================
True Positives: 0
False Positives: 1

Saved inference for lstm_baseline to inference\lstm_baseline.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 3
False Positives: 1
================== Clf Report for BEE (3) ==================
True Positives: 1
False Positives: 1
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 3
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 2
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 2
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 0

Saved inference for cnn_gru to inference\cnn_gru.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 1
============== Clf Report for BASKETBALL (2) ===============
True Positives: 1
False Positives: 3
================== Clf Report for BEE (3) ==================
True Positives: 0
False Positives: 1
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 1
================= Clf Report for BITE (6) ==================
True Positives: 0
False Positives: 1
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 3
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 2

Saved inference for cnn_lstm to inference\cnn_lstm.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 1
False Positives: 1
============== Clf Report for BASKETBALL (2) ===============
True Positives: 0
False Positives: 2
================== Clf Report for BEE (3) ==================
True Positives: 0
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 1
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 2
False Positives: 1
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 1

Saved inference for bi_gru_seq to inference\bi_gru_seq.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 0
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 3
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 0
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 2
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 0
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 0
False Positives: 3
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 0

In [ ]:
from models import CNNBiGRU_diogo

cnn_kwargs = {
    'out_channels': 64,
    'kernel_size': 3,
    'dropout': 0.2,
    'use_pooling': False
}

rnn_kwargs = {
    'num_layers': 1,
    'bidirectional': True,
}

RNN_HIDDEN_SIZE = 256

INPUT_SIZE = 144
NUM_CLASSES = 100
EPOCHS = 100
BATCH_SIZE = 64
LR_MAX = 1e-3
VERBOSE = True

model_name = 'cnn_gru'
cnn_gru = CNNBiGRU_diogo(input_size=INPUT_SIZE, num_classes=NUM_CLASSES)

# cnngru_no_pool_learner = create_fast_trainer(cnn_gru, train_ds, valid_ds, model_name, batch_size=BATCH_SIZE)
# cnngru_no_pool_learner = train_model(cnngru_no_pool_learner, EPOCHS, lr_max=LR_MAX)

In [12]:
inf = get_predictions(cnngru_no_pool_learner, test_ds)
for ind in range(10):
    tp_fp_classification_report(inf, ind)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

================== Clf Report for AXE (0) ==================
True Positives: 2
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 2
============== Clf Report for BASKETBALL (2) ===============
True Positives: 2
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 2
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 1
False Positives: 0
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 2
False Positives: 1
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 2
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 1
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 1

In [16]:
(inf.correct.sum() / inf.shape[0] * 100).item()

68.13725490196079

In [18]:
from models import TemporalConvTransformer, TemporalConvTransformer_B

In [ ]:


NUM_CLASSES = 100
EPOCHS = 100
BATCH_SIZE = 64
LR_MAX = 1e-4
VERBOSE = True

temporal_transformer = TemporalConvTransformer(
    input_dim=144,
    patch_size=4,
    num_patches=4,         # 16 frames / 4 patch size
    embed_dim=512,
    num_heads=4,
    num_layers=4,
    num_classes=NUM_CLASSES,
    dropout=0.35,
    use_seq_final_block=False
)

model_name = 'temporal_transformer_testing'
tt_learner = create_fast_trainer(
    temporal_transformer,  # model
    train_ds=train_ds,
    valid_ds=valid_ds,
    model_name=model_name,
    batch_size=BATCH_SIZE,
    verbose=VERBOSE,
    additional_cbs=[GradientClip(0.1), EarlyStoppingCallback(monitor='valid_loss', patience=10)]
)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x0000020C5299FF10>
cuda:0
cuda:0

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x0000020C529AF0D0>
cuda:0
cuda:0

In [12]:
tt_learner = train_model(tt_learner, EPOCHS, lr_max=LR_MAX)

Better model found at epoch 0 with valid_loss value: 4.6546149253845215.
Better model found at epoch 1 with valid_loss value: 4.593857288360596.
Better model found at epoch 2 with valid_loss value: 4.52822208404541.
Better model found at epoch 3 with valid_loss value: 4.435863018035889.
Better model found at epoch 4 with valid_loss value: 4.296600341796875.
Better model found at epoch 5 with valid_loss value: 4.128057479858398.
Better model found at epoch 6 with valid_loss value: 3.9808852672576904.
Better model found at epoch 7 with valid_loss value: 3.8172197341918945.
Better model found at epoch 8 with valid_loss value: 3.6192004680633545.
Better model found at epoch 9 with valid_loss value: 3.4007441997528076.
Better model found at epoch 10 with valid_loss value: 3.208986759185791.
Better model found at epoch 11 with valid_loss value: 3.007049560546875.
Better model found at epoch 12 with valid_loss value: 2.809192419052124.
Better model found at epoch 13 with valid_loss value: 2.677873134613037.
Better model found at epoch 14 with valid_loss value: 2.4744927883148193.
Better model found at epoch 15 with valid_loss value: 2.3654797077178955.
Better model found at epoch 16 with valid_loss value: 2.209721803665161.
Better model found at epoch 17 with valid_loss value: 2.1284167766571045.
Better model found at epoch 18 with valid_loss value: 2.0475242137908936.
Better model found at epoch 19 with valid_loss value: 1.9854358434677124.
Better model found at epoch 20 with valid_loss value: 1.8799768686294556.
Better model found at epoch 21 with valid_loss value: 1.8038640022277832.
Better model found at epoch 22 with valid_loss value: 1.7675362825393677.
Better model found at epoch 23 with valid_loss value: 1.721899151802063.
Better model found at epoch 24 with valid_loss value: 1.6692761182785034.
Better model found at epoch 26 with valid_loss value: 1.6316832304000854.
Better model found at epoch 27 with valid_loss value: 1.5530914068222046.
Better model found at epoch 30 with valid_loss value: 1.5358902215957642.
Better model found at epoch 31 with valid_loss value: 1.5198307037353516.
Better model found at epoch 32 with valid_loss value: 1.5092216730117798.
Better model found at epoch 36 with valid_loss value: 1.4635272026062012.
Better model found at epoch 40 with valid_loss value: 1.4615198373794556.
Better model found at epoch 41 with valid_loss value: 1.4468766450881958.
Better model found at epoch 45 with valid_loss value: 1.4304494857788086.
No improvement since epoch 45: early stopping

In [13]:
inf = get_predictions(tt_learner, test_ds)
for ind in range(10):
    tp_fp_classification_report(inf, ind)

================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 3
============== Clf Report for BASKETBALL (2) ===============
True Positives: 2
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 2
False Positives: 1
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 2
================ Clf Report for BORROW (8) =================
True Positives: 2
False Positives: 0
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 1

In [21]:
temporal_transformer_b = TemporalConvTransformer_B(
    input_dim=144,
    patch_size=4,
    num_patches=4,         # 16 frames / 4 patch size
    embed_dim=512,
    num_heads=8,
    num_layers=4,
    num_classes=NUM_CLASSES,
    dropout=0.42,
    use_seq_final_block=False,
    use_cls_token=True
)

model_name = 'temporal_transformer_testing_b'
tt2_learner = create_fast_trainer(
    temporal_transformer_b,  # model
    train_ds=train_ds,
    valid_ds=valid_ds,
    model_name=model_name,
    batch_size=BATCH_SIZE,
    verbose=VERBOSE,
    additional_cbs=[GradientClip(0.1), EarlyStoppingCallback(monitor='valid_loss', patience=10)]
)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x0000020CCEF85590>
cuda:0
cuda:0
Found model temporal_transformer_testing_b in the models directory.

In [22]:
tt2_learner = train_model(tt2_learner, EPOCHS, lr_max=LR_MAX)

Better model found at epoch 0 with valid_loss value: 4.687349796295166.
Better model found at epoch 1 with valid_loss value: 4.639741897583008.
Better model found at epoch 2 with valid_loss value: 4.605696201324463.
Better model found at epoch 3 with valid_loss value: 4.57838773727417.
Better model found at epoch 4 with valid_loss value: 4.549538612365723.
Better model found at epoch 5 with valid_loss value: 4.50471305847168.
Better model found at epoch 6 with valid_loss value: 4.405699253082275.
Better model found at epoch 7 with valid_loss value: 4.2358574867248535.
Better model found at epoch 8 with valid_loss value: 4.105769157409668.
Better model found at epoch 9 with valid_loss value: 3.9932260513305664.
Better model found at epoch 10 with valid_loss value: 3.8681640625.
Better model found at epoch 11 with valid_loss value: 3.7311363220214844.
Better model found at epoch 12 with valid_loss value: 3.561633586883545.
Better model found at epoch 13 with valid_loss value: 3.4151551723480225.
Better model found at epoch 14 with valid_loss value: 3.2681238651275635.
Better model found at epoch 15 with valid_loss value: 3.217608690261841.
Better model found at epoch 16 with valid_loss value: 3.031261920928955.
Better model found at epoch 17 with valid_loss value: 2.8696606159210205.
Better model found at epoch 18 with valid_loss value: 2.726207733154297.
Better model found at epoch 19 with valid_loss value: 2.621303081512451.
Better model found at epoch 20 with valid_loss value: 2.526210308074951.
Better model found at epoch 21 with valid_loss value: 2.320323944091797.
Better model found at epoch 22 with valid_loss value: 2.2977914810180664.
Better model found at epoch 23 with valid_loss value: 2.2092461585998535.
Better model found at epoch 24 with valid_loss value: 2.100800037384033.
Better model found at epoch 25 with valid_loss value: 2.0929980278015137.
Better model found at epoch 26 with valid_loss value: 1.9866241216659546.
Better model found at epoch 27 with valid_loss value: 1.911013126373291.
Better model found at epoch 28 with valid_loss value: 1.8564424514770508.
Better model found at epoch 29 with valid_loss value: 1.8086276054382324.
Better model found at epoch 30 with valid_loss value: 1.7837954759597778.
Better model found at epoch 31 with valid_loss value: 1.7070451974868774.
Better model found at epoch 32 with valid_loss value: 1.6978168487548828.
Better model found at epoch 33 with valid_loss value: 1.6518220901489258.
Better model found at epoch 35 with valid_loss value: 1.5912797451019287.
Better model found at epoch 36 with valid_loss value: 1.5859441757202148.
Better model found at epoch 37 with valid_loss value: 1.5693377256393433.
Better model found at epoch 38 with valid_loss value: 1.5654278993606567.
Better model found at epoch 39 with valid_loss value: 1.556875228881836.
Better model found at epoch 41 with valid_loss value: 1.5524730682373047.
Better model found at epoch 43 with valid_loss value: 1.5386656522750854.
Better model found at epoch 44 with valid_loss value: 1.5353161096572876.
Better model found at epoch 45 with valid_loss value: 1.516829490661621.
Better model found at epoch 46 with valid_loss value: 1.4861122369766235.
Better model found at epoch 50 with valid_loss value: 1.4424450397491455.
Better model found at epoch 57 with valid_loss value: 1.431766152381897.
Better model found at epoch 67 with valid_loss value: 1.4073415994644165.
No improvement since epoch 67: early stopping

In [ ]:
inf = get_predictions(tt2_learner, test_ds)
for ind in range(20):
    tp_fp_classification_report(inf, ind)

================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 2
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 1
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 2
False Positives: 1
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 1
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 2
False Positives: 0
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 0

Exporting the best model for the production

In [34]:
model_name = 'temporal_transformer_testing_b'
tt2_learner = create_fast_trainer(
    temporal_transformer_b,  # model
    train_ds=train_ds,
    valid_ds=valid_ds,
    model_name=model_name,
    batch_size=BATCH_SIZE,
    verbose=VERBOSE,
    additional_cbs=[GradientClip(0.1), EarlyStoppingCallback(monitor='valid_loss', patience=10)]
)

model = tt2_learner.model.eval()

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x0000020CDB567710>
cuda:0
cuda:0
Found model temporal_transformer_testing_b in the models directory.

In [36]:
example_inputs = test_ds[0][0].unsqueeze(0).cuda()
save_path = os.path.join('models', "temporal_transformer_b_script.pt")
traced_model = torch.jit.script(model)
traced_model.save(save_path)

Using Cross-fold validation with Participant ID to split the dataset

In [28]:
df = pd.concat([train, val], axis=0)
df.head()

,Participant ID,Video file,Gloss,ASL-LEX Code,label,fpath,prep_fpath,kpts_fpath
0,P22,15252109051698337-NOON.mp4,NOON,G_02_014,66,datasets\ASL-Citizen\top100_videos\15252109051698337-NOON.mp4,datasets\ASL-Citizen\preprocess_videos\15252109051698337-NOON.npy,datasets\ASL-Citizen\keypoints\15252109051698337-NOON.json
1,P22,45069896884439653-SAME 2.mp4,SAME,B_02_013,73,datasets\ASL-Citizen\top100_videos\45069896884439653-SAME 2.mp4,datasets\ASL-Citizen\preprocess_videos\45069896884439653-SAME 2.npy,datasets\ASL-Citizen\keypoints\45069896884439653-SAME 2.json
2,P35,9547038026063932-TEXT.mp4,TEXT,B_03_054,93,datasets\ASL-Citizen\top100_videos\9547038026063932-TEXT.mp4,datasets\ASL-Citizen\preprocess_videos\9547038026063932-TEXT.npy,datasets\ASL-Citizen\keypoints\9547038026063932-TEXT.json
3,P27,09898660662683256-BOWL.mp4,BOWL,C_03_049,10,datasets\ASL-Citizen\top100_videos\09898660662683256-BOWL.mp4,datasets\ASL-Citizen\preprocess_videos\09898660662683256-BOWL.npy,datasets\ASL-Citizen\keypoints\09898660662683256-BOWL.json
4,P47,13651840403204663-ELEVATOR.mp4,ELEVATOR,G_03_036,48,datasets\ASL-Citizen\top100_videos\13651840403204663-ELEVATOR.mp4,datasets\ASL-Citizen\preprocess_videos\13651840403204663-ELEVATOR.npy,datasets\ASL-Citizen\keypoints\13651840403204663-ELEVATOR.json

In [ ]:
model_params = {
    'input_dim':144,
    'patch_size':4,
    'num_patches':4,         # 16 frames / 4 patch size
    'embed_dim':512,
    'num_heads':8,
    'num_layers':4,
    'num_classes':100,
    'dropout':0.42,
    'use_seq_final_block':False,
    'use_cls_token':True
}

# temporal_transformer_b = TemporalConvTransformer_B()

results, summary, indexes = cross_validate_pipeline(df, 
                        df.label.to_list(),
                        df['Participant ID'].to_list(),
                        TemporalConvTransformer_B,
                        model_params,
                        epochs=100,
                        lr_max=1e-4,
                        )

=== Starting fold_1 ===

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x00000258A26FDB50>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.705330848693848.
Better model found at epoch 1 with valid_loss value: 4.650333404541016.
Better model found at epoch 2 with valid_loss value: 4.609676361083984.
Better model found at epoch 3 with valid_loss value: 4.577211380004883.
Better model found at epoch 4 with valid_loss value: 4.54514217376709.
Better model found at epoch 5 with valid_loss value: 4.500874996185303.
Better model found at epoch 6 with valid_loss value: 4.412589073181152.
Better model found at epoch 7 with valid_loss value: 4.273525714874268.
Better model found at epoch 8 with valid_loss value: 4.151106834411621.
Better model found at epoch 9 with valid_loss value: 4.062647819519043.
Better model found at epoch 10 with valid_loss value: 3.9603517055511475.
Better model found at epoch 11 with valid_loss value: 3.8506929874420166.
Better model found at epoch 12 with valid_loss value: 3.7281570434570312.
Better model found at epoch 13 with valid_loss value: 3.5983641147613525.
Better model found at epoch 14 with valid_loss value: 3.4376296997070312.
Better model found at epoch 15 with valid_loss value: 3.3235013484954834.
Better model found at epoch 16 with valid_loss value: 3.2441537380218506.
Better model found at epoch 17 with valid_loss value: 3.114356756210327.
Better model found at epoch 18 with valid_loss value: 3.014545440673828.
Better model found at epoch 19 with valid_loss value: 2.853187322616577.
Better model found at epoch 20 with valid_loss value: 2.819441080093384.
Better model found at epoch 21 with valid_loss value: 2.7382092475891113.
Better model found at epoch 22 with valid_loss value: 2.562394857406616.
Better model found at epoch 23 with valid_loss value: 2.4941818714141846.
Better model found at epoch 24 with valid_loss value: 2.3466100692749023.
Better model found at epoch 26 with valid_loss value: 2.209341049194336.
Better model found at epoch 27 with valid_loss value: 2.1955313682556152.
Better model found at epoch 28 with valid_loss value: 2.0685436725616455.
Better model found at epoch 31 with valid_loss value: 1.986912488937378.
Better model found at epoch 32 with valid_loss value: 1.9686285257339478.
Better model found at epoch 33 with valid_loss value: 1.912792444229126.
Better model found at epoch 34 with valid_loss value: 1.8838621377944946.
Better model found at epoch 36 with valid_loss value: 1.8634445667266846.
Better model found at epoch 38 with valid_loss value: 1.7938965559005737.
Better model found at epoch 41 with valid_loss value: 1.7923390865325928.
Better model found at epoch 44 with valid_loss value: 1.7748767137527466.
Better model found at epoch 45 with valid_loss value: 1.755182147026062.
Better model found at epoch 47 with valid_loss value: 1.7458163499832153.
Better model found at epoch 48 with valid_loss value: 1.724765658378601.
Better model found at epoch 50 with valid_loss value: 1.7105168104171753.
Better model found at epoch 54 with valid_loss value: 1.7074934244155884.
Better model found at epoch 55 with valid_loss value: 1.695336103439331.
Better model found at epoch 57 with valid_loss value: 1.6758217811584473.
Better model found at epoch 66 with valid_loss value: 1.6674447059631348.
Better model found at epoch 75 with valid_loss value: 1.6540061235427856.
Better model found at epoch 83 with valid_loss value: 1.651968002319336.
Better model found at epoch 85 with valid_loss value: 1.6489861011505127.
No improvement since epoch 85: early stopping

fold_1 — Acc@1: 0.6317, Acc@5: 0.8593

=== Starting fold_2 ===

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x00000258A1E61A10>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.696837902069092.
Better model found at epoch 1 with valid_loss value: 4.650517463684082.
Better model found at epoch 2 with valid_loss value: 4.613749980926514.
Better model found at epoch 3 with valid_loss value: 4.582869529724121.
Better model found at epoch 4 with valid_loss value: 4.557772636413574.
Better model found at epoch 5 with valid_loss value: 4.527273178100586.
Better model found at epoch 6 with valid_loss value: 4.4703049659729.
Better model found at epoch 7 with valid_loss value: 4.359119415283203.
Better model found at epoch 8 with valid_loss value: 4.193975925445557.
Better model found at epoch 9 with valid_loss value: 4.058493137359619.
Better model found at epoch 10 with valid_loss value: 3.9382524490356445.
Better model found at epoch 11 with valid_loss value: 3.804328680038452.
Better model found at epoch 12 with valid_loss value: 3.647639036178589.
Better model found at epoch 13 with valid_loss value: 3.494805097579956.
Better model found at epoch 14 with valid_loss value: 3.31010103225708.
Better model found at epoch 15 with valid_loss value: 3.1825568675994873.
Better model found at epoch 16 with valid_loss value: 2.9971344470977783.
Better model found at epoch 17 with valid_loss value: 2.8573896884918213.
Better model found at epoch 18 with valid_loss value: 2.708745002746582.
Better model found at epoch 19 with valid_loss value: 2.608454704284668.
Better model found at epoch 20 with valid_loss value: 2.4801745414733887.
Better model found at epoch 21 with valid_loss value: 2.3455922603607178.
Better model found at epoch 22 with valid_loss value: 2.2514970302581787.
Better model found at epoch 23 with valid_loss value: 2.1353981494903564.
Better model found at epoch 24 with valid_loss value: 2.0757923126220703.
Better model found at epoch 25 with valid_loss value: 1.9939837455749512.
Better model found at epoch 26 with valid_loss value: 1.9124006032943726.
Better model found at epoch 27 with valid_loss value: 1.7983741760253906.
Better model found at epoch 28 with valid_loss value: 1.7910218238830566.
Better model found at epoch 29 with valid_loss value: 1.6570894718170166.
Better model found at epoch 30 with valid_loss value: 1.6427556276321411.
Better model found at epoch 31 with valid_loss value: 1.5482295751571655.
Better model found at epoch 32 with valid_loss value: 1.4827674627304077.
Better model found at epoch 33 with valid_loss value: 1.469712495803833.
Better model found at epoch 34 with valid_loss value: 1.388305902481079.
Better model found at epoch 36 with valid_loss value: 1.3188999891281128.
Better model found at epoch 38 with valid_loss value: 1.2711867094039917.
Better model found at epoch 39 with valid_loss value: 1.2412493228912354.
Better model found at epoch 43 with valid_loss value: 1.2113064527511597.
Better model found at epoch 44 with valid_loss value: 1.1925314664840698.
Better model found at epoch 45 with valid_loss value: 1.154131293296814.
Better model found at epoch 46 with valid_loss value: 1.1475999355316162.
Better model found at epoch 47 with valid_loss value: 1.1314222812652588.
Better model found at epoch 48 with valid_loss value: 1.1268665790557861.
Better model found at epoch 49 with valid_loss value: 1.1240330934524536.
Better model found at epoch 50 with valid_loss value: 1.1238868236541748.
Better model found at epoch 51 with valid_loss value: 1.035579800605774.
Better model found at epoch 56 with valid_loss value: 1.0251929759979248.
Better model found at epoch 57 with valid_loss value: 1.0037672519683838.
Better model found at epoch 62 with valid_loss value: 0.9903186559677124.
Better model found at epoch 63 with valid_loss value: 0.984730064868927.
Better model found at epoch 65 with valid_loss value: 0.984312891960144.
Better model found at epoch 68 with valid_loss value: 0.9672603607177734.
Better model found at epoch 76 with valid_loss value: 0.959109365940094.
Better model found at epoch 79 with valid_loss value: 0.9423614740371704.
No improvement since epoch 79: early stopping

fold_2 — Acc@1: 0.7309, Acc@5: 0.9372

=== Starting fold_3 ===

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x00000258A26E1A10>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.7070841789245605.
Better model found at epoch 1 with valid_loss value: 4.66002082824707.
Better model found at epoch 2 with valid_loss value: 4.6214919090271.
Better model found at epoch 3 with valid_loss value: 4.58883810043335.
Better model found at epoch 4 with valid_loss value: 4.565061569213867.
Better model found at epoch 5 with valid_loss value: 4.523524284362793.
Better model found at epoch 6 with valid_loss value: 4.453124046325684.
Better model found at epoch 7 with valid_loss value: 4.326757907867432.
Better model found at epoch 8 with valid_loss value: 4.208494663238525.
Better model found at epoch 9 with valid_loss value: 4.115095615386963.
Better model found at epoch 10 with valid_loss value: 4.0151896476745605.
Better model found at epoch 11 with valid_loss value: 3.9174206256866455.
Better model found at epoch 12 with valid_loss value: 3.8277807235717773.
Better model found at epoch 13 with valid_loss value: 3.6629419326782227.
Better model found at epoch 14 with valid_loss value: 3.5524215698242188.
Better model found at epoch 15 with valid_loss value: 3.500685691833496.
Better model found at epoch 16 with valid_loss value: 3.3706233501434326.
Better model found at epoch 17 with valid_loss value: 3.2490713596343994.
Better model found at epoch 18 with valid_loss value: 3.189042806625366.
Better model found at epoch 19 with valid_loss value: 3.038625478744507.
Better model found at epoch 20 with valid_loss value: 2.938278913497925.
Better model found at epoch 21 with valid_loss value: 2.83512806892395.
Better model found at epoch 22 with valid_loss value: 2.7161247730255127.
Better model found at epoch 23 with valid_loss value: 2.5949363708496094.
Better model found at epoch 24 with valid_loss value: 2.5277204513549805.
Better model found at epoch 25 with valid_loss value: 2.4792988300323486.
Better model found at epoch 26 with valid_loss value: 2.340033769607544.
Better model found at epoch 27 with valid_loss value: 2.287027597427368.
Better model found at epoch 28 with valid_loss value: 2.286545515060425.
Better model found at epoch 29 with valid_loss value: 2.2266921997070312.
Better model found at epoch 30 with valid_loss value: 2.2088749408721924.
Better model found at epoch 31 with valid_loss value: 2.2023870944976807.
Better model found at epoch 32 with valid_loss value: 2.158993721008301.
Better model found at epoch 33 with valid_loss value: 2.0501437187194824.
Better model found at epoch 35 with valid_loss value: 2.043809413909912.
Better model found at epoch 37 with valid_loss value: 1.9635534286499023.
Better model found at epoch 38 with valid_loss value: 1.916990041732788.
Better model found at epoch 41 with valid_loss value: 1.9128596782684326.
Better model found at epoch 42 with valid_loss value: 1.883813500404358.
Better model found at epoch 43 with valid_loss value: 1.872576117515564.
Better model found at epoch 45 with valid_loss value: 1.8267961740493774.
Better model found at epoch 47 with valid_loss value: 1.815290093421936.
Better model found at epoch 49 with valid_loss value: 1.8136794567108154.
Better model found at epoch 54 with valid_loss value: 1.813477635383606.
Better model found at epoch 56 with valid_loss value: 1.7839373350143433.
Better model found at epoch 59 with valid_loss value: 1.778437614440918.
Better model found at epoch 69 with valid_loss value: 1.769025206565857.
No improvement since epoch 69: early stopping

fold_3 — Acc@1: 0.6108, Acc@5: 0.8383

=== Starting fold_4 ===

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x00000258A28FBE90>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.697072982788086.
Better model found at epoch 1 with valid_loss value: 4.6484456062316895.
Better model found at epoch 2 with valid_loss value: 4.612095832824707.
Better model found at epoch 3 with valid_loss value: 4.586426258087158.
Better model found at epoch 4 with valid_loss value: 4.559258460998535.
Better model found at epoch 5 with valid_loss value: 4.524668216705322.
Better model found at epoch 6 with valid_loss value: 4.45814323425293.
Better model found at epoch 7 with valid_loss value: 4.33960485458374.
Better model found at epoch 8 with valid_loss value: 4.171579837799072.
Better model found at epoch 9 with valid_loss value: 4.040754795074463.
Better model found at epoch 10 with valid_loss value: 3.9183266162872314.
Better model found at epoch 11 with valid_loss value: 3.798534393310547.
Better model found at epoch 12 with valid_loss value: 3.6532249450683594.
Better model found at epoch 13 with valid_loss value: 3.468148708343506.
Better model found at epoch 14 with valid_loss value: 3.325087785720825.
Better model found at epoch 15 with valid_loss value: 3.2358336448669434.
Better model found at epoch 16 with valid_loss value: 3.0513691902160645.
Better model found at epoch 17 with valid_loss value: 2.9657912254333496.
Better model found at epoch 18 with valid_loss value: 2.8225862979888916.
Better model found at epoch 19 with valid_loss value: 2.7052388191223145.
Better model found at epoch 20 with valid_loss value: 2.5023670196533203.
Better model found at epoch 21 with valid_loss value: 2.351104736328125.
Better model found at epoch 22 with valid_loss value: 2.249324083328247.
Better model found at epoch 23 with valid_loss value: 2.1878724098205566.
Better model found at epoch 24 with valid_loss value: 2.10834002494812.
Better model found at epoch 25 with valid_loss value: 2.0371668338775635.
Better model found at epoch 26 with valid_loss value: 1.966752052307129.
Better model found at epoch 27 with valid_loss value: 1.8541663885116577.
Better model found at epoch 28 with valid_loss value: 1.852726697921753.
Better model found at epoch 29 with valid_loss value: 1.8344061374664307.
Better model found at epoch 30 with valid_loss value: 1.7414110898971558.
Better model found at epoch 31 with valid_loss value: 1.640415906906128.
Better model found at epoch 33 with valid_loss value: 1.5733072757720947.
Better model found at epoch 34 with valid_loss value: 1.5284918546676636.
Better model found at epoch 36 with valid_loss value: 1.52766752243042.
Better model found at epoch 37 with valid_loss value: 1.4371743202209473.
Better model found at epoch 38 with valid_loss value: 1.419763445854187.
Better model found at epoch 39 with valid_loss value: 1.4003262519836426.
Better model found at epoch 40 with valid_loss value: 1.3322614431381226.
Better model found at epoch 45 with valid_loss value: 1.274868130683899.
Better model found at epoch 49 with valid_loss value: 1.2224147319793701.
Better model found at epoch 56 with valid_loss value: 1.2074975967407227.
Better model found at epoch 57 with valid_loss value: 1.1773070096969604.
Better model found at epoch 58 with valid_loss value: 1.171115517616272.
Better model found at epoch 59 with valid_loss value: 1.1578831672668457.
Better model found at epoch 67 with valid_loss value: 1.1500364542007446.
Better model found at epoch 73 with valid_loss value: 1.1464298963546753.
Better model found at epoch 76 with valid_loss value: 1.1432923078536987.
Better model found at epoch 80 with valid_loss value: 1.132622480392456.
No improvement since epoch 80: early stopping

fold_4 — Acc@1: 0.6976, Acc@5: 0.9147

=== Starting fold_5 ===

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x00000258015CB1D0>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.69866943359375.
Better model found at epoch 1 with valid_loss value: 4.651693820953369.
Better model found at epoch 2 with valid_loss value: 4.616652011871338.
Better model found at epoch 3 with valid_loss value: 4.587954044342041.
Better model found at epoch 4 with valid_loss value: 4.565186500549316.
Better model found at epoch 5 with valid_loss value: 4.539784908294678.
Better model found at epoch 6 with valid_loss value: 4.491002082824707.
Better model found at epoch 7 with valid_loss value: 4.388883113861084.
Better model found at epoch 8 with valid_loss value: 4.238253593444824.
Better model found at epoch 9 with valid_loss value: 4.138255596160889.
Better model found at epoch 10 with valid_loss value: 4.022351264953613.
Better model found at epoch 11 with valid_loss value: 3.9236297607421875.
Better model found at epoch 12 with valid_loss value: 3.8717148303985596.
Better model found at epoch 13 with valid_loss value: 3.7418174743652344.
Better model found at epoch 14 with valid_loss value: 3.586817741394043.
Better model found at epoch 15 with valid_loss value: 3.4439196586608887.
Better model found at epoch 16 with valid_loss value: 3.325204849243164.
Better model found at epoch 17 with valid_loss value: 3.255890130996704.
Better model found at epoch 18 with valid_loss value: 3.098771572113037.
Better model found at epoch 19 with valid_loss value: 3.04691481590271.
Better model found at epoch 20 with valid_loss value: 2.896040678024292.
Better model found at epoch 21 with valid_loss value: 2.7789082527160645.
Better model found at epoch 22 with valid_loss value: 2.7513322830200195.
Better model found at epoch 23 with valid_loss value: 2.7119290828704834.
Better model found at epoch 24 with valid_loss value: 2.5683116912841797.
Better model found at epoch 25 with valid_loss value: 2.465243339538574.
Better model found at epoch 26 with valid_loss value: 2.434865951538086.
Better model found at epoch 27 with valid_loss value: 2.4285337924957275.
Better model found at epoch 28 with valid_loss value: 2.3058106899261475.
Better model found at epoch 29 with valid_loss value: 2.262584924697876.
Better model found at epoch 31 with valid_loss value: 2.2416422367095947.
Better model found at epoch 32 with valid_loss value: 2.1703240871429443.
Better model found at epoch 34 with valid_loss value: 2.1601438522338867.
Better model found at epoch 35 with valid_loss value: 2.0887222290039062.
Better model found at epoch 38 with valid_loss value: 2.034179925918579.
Better model found at epoch 40 with valid_loss value: 2.0086374282836914.
Better model found at epoch 43 with valid_loss value: 1.9804972410202026.
Better model found at epoch 51 with valid_loss value: 1.9296895265579224.
Better model found at epoch 59 with valid_loss value: 1.9091441631317139.
No improvement since epoch 59: early stopping

fold_5 — Acc@1: 0.5217, Acc@5: 0.8096

Best fold: fold_2 with Acc@1: 0.7309

In [56]:
results

   fold      acc1      acc5
0     1  0.631737  0.859281
1     2  0.730942  0.937220
2     3  0.610778  0.838323
3     4  0.697605  0.914671
4     5  0.521739  0.809595

In [57]:
summary

{'fold': 'mean/std', 'acc1': '0.6386 ± 0.0814', 'acc5': '0.8718 ± 0.0531'}

In [60]:
np.save('train_idx.npy', indexes[1][1])
np.save('valid_idx.npy', indexes[1][2])

In [17]:
model_name = 'fold_2'

model_params = {
    'input_dim':144,
    'patch_size':4,
    'num_patches':4,         # 16 frames / 4 patch size
    'embed_dim':512,
    'num_heads':8,
    'num_layers':4,
    'num_classes':100,
    'dropout':0.42,
    'use_seq_final_block':False,
    'use_cls_token':True
}
tempcnn = TemporalConvTransformer_B(**model_params)
tt2_learner = create_fast_trainer(
    tempcnn,  # model
    train_ds=train_ds,
    valid_ds=valid_ds,
    model_name=model_name,
    batch_size=64,
    verbose=True,
    additional_cbs=[GradientClip(0.1), EarlyStoppingCallback(monitor='valid_loss', patience=10)]
)

model = tt2_learner.model.eval()

NameError: name 'TemporalConvTransformer_B' is not defined

In [64]:
p = get_predictions(tt2_learner, test_ds)
p.correct.sum() / p.shape[0]

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

np.float64(0.9264705882352942)

In [65]:
example_inputs = test_ds[0][0].unsqueeze(0).cuda()
save_path = os.path.join('models', "temporal_transformer_b_best_script.pt")
traced_model = torch.jit.script(model)
traced_model.save(save_path)

In [68]:
p[p.correct == False].sort_values(by='true_class')

     pred  true    pred_class    true_class  correct
140    15     3     BREAKFAST           BEE    False
136     2    13    BASKETBALL        BRAIDS    False
157    74    15      SANDWICH     BREAKFAST    False
2      32    18          CITY        CANCER    False
193    31    28     CIGARETTE  CHEESEGRATER    False
40      5    39          BELT        DECIDE    False
75     70    45      RESEARCH          DRAG    False
117    45    51          DRAG          GIFT    False
35     97    63         TWINS    MICROSCOPE    False
151    89    66       SUSPECT          NOON    False
196    80    70          SHOP      RESEARCH    False
54      5    73          BELT          SAME    False
201    38    73          DEAF          SAME    False
170    28    81  CHEESEGRATER          SINK    False
83     11    91        BOXING          TEAM    False

In [21]:
model_params = {
    'input_dim':144,
    'patch_size':4,
    'num_patches':4,         # 16 frames / 4 patch size
    'embed_dim':512,
    'num_heads':8,
    'num_layers':4,
    'num_classes':100,
    'dropout':0.42,
    'use_seq_final_block':False,
    'use_cls_token':True
}

tempcnn = TemporalConvTransformer_B(**model_params)

models = [
    ('gru_baseline', gru_model),
    ('lstm_baseline', lstm_model),
    ('cnn_gru', cnn_gru),
    ('cnn_lstm', cnn_lstm),
    ('bi_gru_seq', gru_seq),
    ('fold_2', tempcnn)
]

classifications = []

for name, model in models:
    learner = create_fast_trainer(model, train_ds, valid_ds, name, load_saved_model=True)
    inference = get_predictions(learner, test_ds)
    clfs = []
    for ind in range(100):
        total, tp, fp = tp_fp_classification_report(inference, ind, return_metrics=True)
        clfs.append([ind, tp, fp, total])
    classifications.append([name, clfs])

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'GRUModel' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002DD4527D0D0>
cuda:0
cuda:0
Found model gru_baseline in the models directory.

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'LSTMModel' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002DD4692B610>
cuda:0
cuda:0
Found model lstm_baseline in the models directory.

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNBiGRU_diogo' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002DD468F6F50>
cuda:0
cuda:0
Found model cnn_gru in the models directory.

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNRNN' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002DD468F01D0>
cuda:0
cuda:0
Found model cnn_lstm in the models directory.

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'BiGRUWithSeq' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002DD4526FA90>
cuda:0
cuda:0
Found model bi_gru_seq in the models directory.

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer_B' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002DD468F6590>
cuda:0
cuda:0
Found model fold_2 in the models directory.

In [27]:
for model, clfs in classifications:
    d = pd.DataFrame(clfs, columns=['class_index', 'tp', 'fp', 'total samples'])

    print(f' Model : {model} '.center(60, '='))
    print()
    print(' Top 5 classes with True Positives '.center(60, '='))
    print(d.sort_values(by='tp', ascending=False).head())
    print()
    print(' Top 5 classes with False Positives '.center(60, '='))
    print(d.sort_values(by='fp', ascending=False).head())

    print()

=================== Model : gru_baseline ===================

============ Top 5 classes with True Positives =============
    class_index   tp        fp  total samples
0             0  1.0  0.500000              2
19           19  1.0  0.000000              2
7             7  1.0  1.500000              2
5             5  1.0  0.666667              3
29           29  1.0  0.000000              2

============ Top 5 classes with False Positives ============
    class_index   tp   fp  total samples
3             3  0.5  5.0              2
49           49  1.0  4.5              2
69           69  1.0  3.5              2
46           46  0.5  2.0              2
43           43  1.0  2.0              2

================== Model : lstm_baseline ===================

============ Top 5 classes with True Positives =============
    class_index   tp        fp  total samples
1             1  1.0  0.000000              2
2             2  1.0  0.333333              3
7             7  1.0  0.500000              2
5             5  1.0  0.000000              3
24           24  1.0  0.000000              2

============ Top 5 classes with False Positives ============
    class_index   tp   fp  total samples
61           61  0.0  3.5              2
4             4  0.0  1.5              2
41           41  0.5  1.5              2
53           53  0.5  1.5              2
59           59  0.5  1.5              2

===================== Model : cnn_gru ======================

============ Top 5 classes with True Positives =============
    class_index   tp        fp  total samples
3             3  1.0  0.000000              2
10           10  1.0  0.500000              2
7             7  1.0  0.500000              2
5             5  1.0  0.333333              3
31           31  1.0  0.000000              2

============ Top 5 classes with False Positives ============
    class_index   tp   fp  total samples
17           17  0.5  1.5              2
41           41  0.5  1.5              2
11           11  0.5  1.0              2
32           32  1.0  1.0              2
68           68  1.0  1.0              3

===================== Model : cnn_lstm =====================

============ Top 5 classes with True Positives =============
    class_index   tp        fp  total samples
18           18  1.0  0.500000              2
10           10  1.0  0.000000              2
8             8  1.0  0.500000              2
5             5  1.0  0.333333              3
29           29  1.0  1.000000              2

============ Top 5 classes with False Positives ============
    class_index   tp   fp  total samples
23           23  0.5  2.0              2
69           69  0.5  2.0              2
17           17  0.0  1.5              2
15           15  0.5  1.5              2
35           35  1.0  1.5              2

==================== Model : bi_gru_seq ====================

============ Top 5 classes with True Positives =============
    class_index   tp   fp  total samples
2             2  1.0  0.0              3
34           34  1.0  6.5              2
12           12  1.0  7.5              2
10           10  1.0  1.0              2
35           35  1.0  0.0              2

============ Top 5 classes with False Positives ============
    class_index   tp    fp  total samples
49           49  1.0  13.5              2
12           12  1.0   7.5              2
67           67  1.0   7.5              2
61           61  0.0   7.0              2
34           34  1.0   6.5              2

====================== Model : fold_2 ======================

============ Top 5 classes with True Positives =============
    class_index   tp        fp  total samples
0             0  1.0  0.000000              2
1             1  1.0  0.000000              2
2             2  1.0  0.333333              3
4             4  1.0  0.000000              2
29           29  1.0  0.000000              2

============ Top 5 classes with False Positives ============
    class_index   tp        fp  total samples
5             5  1.0  0.666667              3
31           31  1.0  0.500000              2
11           11  1.0  0.500000              2
15           15  0.5  0.500000              2
32           32  1.0  0.500000              2