In [1]:
import os
import pandas as pd 
import cv2
import json 


def read_json(fname):
    with open(fname, 'r') as f:
        return json.load(f)

In [2]:
def get_label_gloss_mappings(df):
    """
    Creates two dictionaries:
    - label_to_gloss: maps label index to gloss name
    - gloss_to_label: maps gloss name to label index

    Args:
        df (pd.DataFrame): DataFrame with 'gloss' and 'label' columns.

    Returns:
        dict, dict: (label_to_gloss, gloss_to_label)
    """
    label_to_gloss = dict(df[['label', 'Gloss']].drop_duplicates().sort_values('label').values)
    gloss_to_label = dict(df[['Gloss', 'label']].drop_duplicates().sort_values('label').values)
    return label_to_gloss, gloss_to_label

In [3]:
dataset_root = os.path.join('datasets', 'ASL-Citizen')
ttv = ['train.csv', 'test.csv', 'val.csv']
train, test, val = [pd.read_csv(os.path.join(dataset_root, i)) for i in ttv]

In [4]:
test.head()

,Participant ID,Video file,Gloss,ASL-LEX Code,label,fpath,prep_fpath,kpts_fpath
0,P48,46041911247233713-HAMMER.mp4,HAMMER,C_02_021,56,datasets\ASL-Citizen\top100_videos\46041911247...,datasets\ASL-Citizen\preprocess_videos\4604191...,datasets\ASL-Citizen\keypoints\460419112472337...
1,P7,014770041748456197-MOVIE.mp4,MOVIE,B_03_077,64,datasets\ASL-Citizen\top100_videos\01477004174...,datasets\ASL-Citizen\preprocess_videos\0147700...,datasets\ASL-Citizen\keypoints\014770041748456...
2,P42,8372181221997397-SERVE 1.mp4,SERVE,E_02_004,76,datasets\ASL-Citizen\top100_videos\83721812219...,datasets\ASL-Citizen\preprocess_videos\8372181...,datasets\ASL-Citizen\keypoints\837218122199739...
3,P29,6422461467297818-CIGARETTE.mp4,CIGARETTE,C_01_059,31,datasets\ASL-Citizen\top100_videos\64224614672...,datasets\ASL-Citizen\preprocess_videos\6422461...,datasets\ASL-Citizen\keypoints\642246146729781...
4,P18,04600046798432267-THAT.mp4,THAT,C_03_059,94,datasets\ASL-Citizen\top100_videos\04600046798...,datasets\ASL-Citizen\preprocess_videos\0460004...,datasets\ASL-Citizen\keypoints\046000467984322...

In [5]:
from data_loader import MSASLKeypointsDataset16Frames

In [6]:
get_fname = lambda x: os.path.basename(x).split('.')[0]
add_ext = lambda x, ext = '.json': x + ext

train_fnames = train['fpath'].apply(get_fname).apply(add_ext)
val_fnames = val['fpath'].apply(get_fname).apply(add_ext)
test_fnames = test['fpath'].apply(get_fname).apply(add_ext)
root_dir = os.path.join(dataset_root, 'top100_videos_16frames_kpts')

In [7]:
train_ds = MSASLKeypointsDataset16Frames(
    root_dir,
    train_fnames,
    train.label.to_list()
    )

valid_ds = MSASLKeypointsDataset16Frames(
    root_dir,
    val_fnames,
    val.label.to_list()
)

test_ds = MSASLKeypointsDataset16Frames(
    root_dir,
    test_fnames,
    test.label.to_list()
)

In [8]:
train_ds[0][0].shape

torch.Size([16, 144])

In [9]:
import torch
from torch.utils.data import DataLoader
from fastai.data.core import DataLoaders
from fastai.callback.tensorboard import TensorBoardCallback
from fastai.callback.tracker import SaveModelCallback
from models import GRUModel, LSTMModel, CNNRNN, BiGRUWithSeq
from fastai.learner import Learner
from fastai.metrics import accuracy, top_k_accuracy, F1ScoreMulti
from fastai.losses import CrossEntropyLossFlat
from sklearn.metrics import f1_score
from fastai.metrics import AccumMetric

def f1_score_flat(preds, targs, average='macro'):
    preds = preds.argmax(dim=1).cpu().numpy()  # Convert from logits to predicted classes
    targs = targs.cpu().numpy()                # Ensure targets are numpy arrays
    print(preds)
    print(targs)
    return f1_score(targs, preds, average=average)

In [10]:
get_available_device_name = lambda learn : next(learn.model.parameters()).device
get_available_dtype = lambda learn : next(learn.model.parameters()).dtype

def create_loggers(model_name):
    """
    Creates TensorBoard and model save callbacks for logging.

    Args:
        model_name (str): Name of the model.

    Returns:
        TensorBoardCallback, SaveModelCallback: Callbacks for logging.
    """
    log_dir = os.path.join('logs', model_name)
    os.makedirs('models', exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)
    tb_logger = TensorBoardCallback(log_dir=log_dir, trace_model=False, log_preds=False)
    save_model = SaveModelCallback(monitor='valid_loss', fname=model_name, with_opt=True)
    return tb_logger, save_model

def create_fast_trainer(model: torch.nn.Module, train_ds, valid_ds, model_name, batch_size = 64, verbose = True):
    tb_logger, save_model = create_loggers(model_name)
    dls = DataLoaders.from_dsets(train_ds, valid_ds, bs=batch_size, shuffle_train=True)
    learner = Learner(
        dls.cuda(),  
        model.cuda(),
        loss_func=CrossEntropyLossFlat(),
        metrics=[accuracy, top_k_accuracy],
        cbs=[tb_logger, save_model],
    ).to_fp16()

    torch.backends.cuda.matmul.allow_tf32 = True
    learner.create_opt()

    if verbose:
        try:
            print(learner.summary())
        except Exception as e:
            print(f"Error in summary: {e}")
        print(get_available_device_name(learner))
        print(get_available_dtype(learner))  # Should show torch.float32
        print(learner.opt)  # Should show "MixedPrecision" in callback list
        print(learner.dls.device)
        print(dls.one_batch()[0].device)

    if f'{model_name}.pth' in os.listdir('models'):
        print(f"Found model {model_name} in the models directory.")
        choice = input("Load the model from the directory ? (y/n) : ")
        if choice == 'y':
            learner.load(model_name, with_opt=True)

    return learner

def train_model(learner : Learner, epochs, lr_max = 1e-3):
    learner.fit_one_cycle(epochs, lr_max=lr_max)
    return learner

lbl_to_gloss,_ = get_label_gloss_mappings(train)
def get_predictions(learner, test_ds = None):
    """
    Get predictions from the model.

    Args:
        learner (Learner): The trained model.
        test_ds (Dataset, optional): Test dataset. Defaults to None.

    Returns:
        list: List of predictions.
    """
    if test_ds is None:
        test_dl = learner.dls.test_dl(test_ds, shuffle=False)
        preds, true = learner.get_preds(dl=test_dl)
    else:
        preds, true = learner.get_preds()
    p, t = torch.argmax(preds, dim=1).tolist(), true.tolist()
    inference = pd.DataFrame({'pred': p, 'true': t})
    inference['pred_class'] = inference['pred'].map(lbl_to_gloss)
    inference['true_class'] = inference['true'].map(lbl_to_gloss)
    inference['correct'] = inference['pred'] == inference['true']
    return inference

def tp_fp_classification_report(inference, class_index):
    tp = inference[(inference['pred'] == class_index) & (inference['true'] == class_index)].shape[0]
    fp = inference[(inference['pred'] == class_index) & (inference['true'] != class_index)].shape[0]
    print(f" Clf Report for {lbl_to_gloss[class_index]} ({class_index}) ".center(60, '='))
    print(f"True Positives: {tp}")
    print(f"False Positives: {fp}")

In [11]:
cnn_kwargs = {
    'out_channels': 128,
    'kernel_size': 3,
    'dropout': 0.1,
    'use_pooling': True
}

rnn_kwargs = {
    'num_layers': 1,
    'dropout': 0.2,
    'bidirectional': True,
}

RNN_HIDDEN_SIZE = 256

INPUT_SIZE = 144
NUM_CLASSES = 100
EPOCHS = 100
BATCH_SIZE = 64
LR_MAX = 1e-3
VERBOSE = True

In [56]:
gru_model = GRUModel(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, rnn_hidden_size=RNN_HIDDEN_SIZE, kwargs={'rnn_kwargs': rnn_kwargs}) # baseline model
lstm_model = LSTMModel(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, rnn_hidden_size=RNN_HIDDEN_SIZE, kwargs={'rnn_kwargs': rnn_kwargs})
cnn_gru = CNNRNN(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, num_cnn_blocks=1, use_lstm=False, rnn_hidden_size=RNN_HIDDEN_SIZE, 
                kwargs={'cnn_kwargs': cnn_kwargs, 'rnn_kwargs': rnn_kwargs})
cnn_lstm = CNNRNN(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, num_cnn_blocks=1, use_lstm=True,  rnn_hidden_size=RNN_HIDDEN_SIZE, 
                kwargs={'cnn_kwargs': cnn_kwargs, 'rnn_kwargs': rnn_kwargs})
gru_seq = BiGRUWithSeq(input_size=INPUT_SIZE, num_classes=NUM_CLASSES, num_layers=2)

In [57]:
models = [
    ('gru_baseline', gru_model),
    ('lstm_baseline', lstm_model),
    ('cnn_gru', cnn_gru),
    ('cnn_lstm', cnn_lstm),
    ('bi_gru_seq', gru_seq)
]
Learners = []
inferences = []
for model_name, model in models:
    print(f" {model_name} ".center(60, '='))
    learner = create_fast_trainer(model, train_ds, valid_ds, model_name, batch_size=BATCH_SIZE, verbose=VERBOSE)
    learner = train_model(learner, EPOCHS, lr_max=LR_MAX)
    inference = get_predictions(learner, test_ds)
    Learners.append((model_name, learner))
    inferences.append((model_name, inference))
    print()

======================= gru_baseline =======================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'GRUModel' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD11630F10>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.60671854019165.
Better model found at epoch 1 with valid_loss value: 4.605711460113525.
Better model found at epoch 2 with valid_loss value: 4.604403495788574.
Better model found at epoch 3 with valid_loss value: 4.602372169494629.
Better model found at epoch 4 with valid_loss value: 4.598360061645508.
Better model found at epoch 5 with valid_loss value: 4.574693202972412.
Better model found at epoch 6 with valid_loss value: 4.446888446807861.
Better model found at epoch 7 with valid_loss value: 4.35939884185791.
Better model found at epoch 8 with valid_loss value: 4.320028305053711.
Better model found at epoch 9 with valid_loss value: 4.295571327209473.
Better model found at epoch 10 with valid_loss value: 4.256669521331787.
Better model found at epoch 11 with valid_loss value: 4.204994201660156.
Better model found at epoch 12 with valid_loss value: 4.140260219573975.
Better model found at epoch 13 with valid_loss value: 4.093429088592529.
Better model found at epoch 14 with valid_loss value: 4.036839962005615.
Better model found at epoch 15 with valid_loss value: 3.974569320678711.
Better model found at epoch 16 with valid_loss value: 3.9421722888946533.
Better model found at epoch 17 with valid_loss value: 3.8559696674346924.
Better model found at epoch 18 with valid_loss value: 3.819803237915039.
Better model found at epoch 19 with valid_loss value: 3.771461248397827.
Better model found at epoch 20 with valid_loss value: 3.7244226932525635.
Better model found at epoch 21 with valid_loss value: 3.649507761001587.
Better model found at epoch 22 with valid_loss value: 3.6123337745666504.
Better model found at epoch 23 with valid_loss value: 3.5821611881256104.
Better model found at epoch 24 with valid_loss value: 3.5270862579345703.
Better model found at epoch 25 with valid_loss value: 3.514861822128296.
Better model found at epoch 26 with valid_loss value: 3.4589738845825195.
Better model found at epoch 27 with valid_loss value: 3.417797565460205.
Better model found at epoch 28 with valid_loss value: 3.37988543510437.
Better model found at epoch 29 with valid_loss value: 3.364691972732544.
Better model found at epoch 30 with valid_loss value: 3.354372262954712.
Better model found at epoch 31 with valid_loss value: 3.3208186626434326.
Better model found at epoch 32 with valid_loss value: 3.251086950302124.
Better model found at epoch 33 with valid_loss value: 3.232905387878418.
Better model found at epoch 34 with valid_loss value: 3.2202680110931396.
Better model found at epoch 35 with valid_loss value: 3.205230474472046.
Better model found at epoch 36 with valid_loss value: 3.187246322631836.
Better model found at epoch 37 with valid_loss value: 3.1469244956970215.
Better model found at epoch 39 with valid_loss value: 3.08274507522583.
Better model found at epoch 42 with valid_loss value: 3.040085554122925.
Better model found at epoch 44 with valid_loss value: 2.997288465499878.
Better model found at epoch 46 with valid_loss value: 2.9911439418792725.
Better model found at epoch 48 with valid_loss value: 2.9510200023651123.
Better model found at epoch 49 with valid_loss value: 2.945988655090332.
Better model found at epoch 50 with valid_loss value: 2.919400691986084.
Better model found at epoch 52 with valid_loss value: 2.9027109146118164.
Better model found at epoch 53 with valid_loss value: 2.887871503829956.
Better model found at epoch 54 with valid_loss value: 2.887350082397461.
Better model found at epoch 56 with valid_loss value: 2.8703911304473877.
Better model found at epoch 57 with valid_loss value: 2.853449583053589.
Better model found at epoch 59 with valid_loss value: 2.8196849822998047.
Better model found at epoch 60 with valid_loss value: 2.816202163696289.
Better model found at epoch 62 with valid_loss value: 2.810925006866455.
Better model found at epoch 63 with valid_loss value: 2.7962327003479004.
Better model found at epoch 66 with valid_loss value: 2.78694748878479.
Better model found at epoch 67 with valid_loss value: 2.786266803741455.
Better model found at epoch 68 with valid_loss value: 2.7816412448883057.
Better model found at epoch 69 with valid_loss value: 2.7751336097717285.
Better model found at epoch 70 with valid_loss value: 2.755192518234253.
Better model found at epoch 76 with valid_loss value: 2.743054151535034.
Better model found at epoch 77 with valid_loss value: 2.7409231662750244.
Better model found at epoch 81 with valid_loss value: 2.7380640506744385.
Better model found at epoch 82 with valid_loss value: 2.724998712539673.
Better model found at epoch 94 with valid_loss value: 2.7242915630340576.

====================== lstm_baseline =======================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'LSTMModel' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD138A40D0>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.608165264129639.
Better model found at epoch 1 with valid_loss value: 4.60771369934082.
Better model found at epoch 2 with valid_loss value: 4.607104301452637.
Better model found at epoch 3 with valid_loss value: 4.606067657470703.
Better model found at epoch 4 with valid_loss value: 4.603183746337891.
Better model found at epoch 5 with valid_loss value: 4.560542583465576.
Better model found at epoch 6 with valid_loss value: 4.465068340301514.
Better model found at epoch 7 with valid_loss value: 4.389425754547119.
Better model found at epoch 8 with valid_loss value: 4.325656890869141.
Better model found at epoch 9 with valid_loss value: 4.272026538848877.
Better model found at epoch 10 with valid_loss value: 4.210241794586182.
Better model found at epoch 11 with valid_loss value: 4.182412147521973.
Better model found at epoch 12 with valid_loss value: 4.146559238433838.
Better model found at epoch 13 with valid_loss value: 4.092617034912109.
Better model found at epoch 14 with valid_loss value: 4.026493072509766.
Better model found at epoch 15 with valid_loss value: 3.9627349376678467.
Better model found at epoch 16 with valid_loss value: 3.9042108058929443.
Better model found at epoch 17 with valid_loss value: 3.8545308113098145.
Better model found at epoch 18 with valid_loss value: 3.8187711238861084.
Better model found at epoch 19 with valid_loss value: 3.717080593109131.
Better model found at epoch 21 with valid_loss value: 3.61370587348938.
Better model found at epoch 22 with valid_loss value: 3.5989654064178467.
Better model found at epoch 23 with valid_loss value: 3.5763957500457764.
Better model found at epoch 24 with valid_loss value: 3.542142391204834.
Better model found at epoch 25 with valid_loss value: 3.5333895683288574.
Better model found at epoch 26 with valid_loss value: 3.4258131980895996.
Better model found at epoch 27 with valid_loss value: 3.3381853103637695.
Better model found at epoch 28 with valid_loss value: 3.3193349838256836.
Better model found at epoch 29 with valid_loss value: 3.3073623180389404.
Better model found at epoch 30 with valid_loss value: 3.2394468784332275.
Better model found at epoch 31 with valid_loss value: 3.213623046875.
Better model found at epoch 33 with valid_loss value: 3.101043939590454.
Better model found at epoch 36 with valid_loss value: 3.066991090774536.
Better model found at epoch 37 with valid_loss value: 3.005504608154297.
Better model found at epoch 38 with valid_loss value: 2.9887590408325195.
Better model found at epoch 39 with valid_loss value: 2.9480412006378174.
Better model found at epoch 40 with valid_loss value: 2.905041456222534.
Better model found at epoch 41 with valid_loss value: 2.8946635723114014.
Better model found at epoch 43 with valid_loss value: 2.8228864669799805.
Better model found at epoch 45 with valid_loss value: 2.771669387817383.
Better model found at epoch 46 with valid_loss value: 2.734652280807495.
Better model found at epoch 48 with valid_loss value: 2.693735122680664.
Better model found at epoch 49 with valid_loss value: 2.647834539413452.
Better model found at epoch 52 with valid_loss value: 2.622049331665039.
Better model found at epoch 53 with valid_loss value: 2.5999319553375244.
Better model found at epoch 55 with valid_loss value: 2.5603718757629395.
Better model found at epoch 57 with valid_loss value: 2.556966781616211.
Better model found at epoch 58 with valid_loss value: 2.512892723083496.
Better model found at epoch 60 with valid_loss value: 2.4721240997314453.
Better model found at epoch 62 with valid_loss value: 2.456270694732666.
Better model found at epoch 63 with valid_loss value: 2.4372615814208984.
Better model found at epoch 65 with valid_loss value: 2.429255247116089.
Better model found at epoch 66 with valid_loss value: 2.417311906814575.
Better model found at epoch 67 with valid_loss value: 2.398876190185547.
Better model found at epoch 69 with valid_loss value: 2.353548288345337.
Better model found at epoch 71 with valid_loss value: 2.346367597579956.
Better model found at epoch 74 with valid_loss value: 2.3435184955596924.
Better model found at epoch 76 with valid_loss value: 2.3245959281921387.
Better model found at epoch 78 with valid_loss value: 2.298381805419922.
Better model found at epoch 79 with valid_loss value: 2.298001527786255.
Better model found at epoch 80 with valid_loss value: 2.2914230823516846.
Better model found at epoch 82 with valid_loss value: 2.281449317932129.
Better model found at epoch 84 with valid_loss value: 2.2782397270202637.
Better model found at epoch 88 with valid_loss value: 2.2730984687805176.
Better model found at epoch 96 with valid_loss value: 2.2720370292663574.

========================= cnn_gru ==========================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNRNN' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD13975F10>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.602174758911133.
Better model found at epoch 1 with valid_loss value: 4.588860511779785.
Better model found at epoch 2 with valid_loss value: 4.574275970458984.
Better model found at epoch 3 with valid_loss value: 4.549103736877441.
Better model found at epoch 4 with valid_loss value: 4.498546600341797.
Better model found at epoch 5 with valid_loss value: 4.4062981605529785.
Better model found at epoch 6 with valid_loss value: 4.296168327331543.
Better model found at epoch 7 with valid_loss value: 4.193922996520996.
Better model found at epoch 8 with valid_loss value: 4.092860698699951.
Better model found at epoch 9 with valid_loss value: 4.000340938568115.
Better model found at epoch 10 with valid_loss value: 3.8971359729766846.
Better model found at epoch 11 with valid_loss value: 3.8060691356658936.
Better model found at epoch 12 with valid_loss value: 3.71980357170105.
Better model found at epoch 13 with valid_loss value: 3.6328628063201904.
Better model found at epoch 14 with valid_loss value: 3.541642665863037.
Better model found at epoch 15 with valid_loss value: 3.489656686782837.
Better model found at epoch 16 with valid_loss value: 3.3971145153045654.
Better model found at epoch 17 with valid_loss value: 3.341613531112671.
Better model found at epoch 18 with valid_loss value: 3.291131019592285.
Better model found at epoch 19 with valid_loss value: 3.2373809814453125.
Better model found at epoch 20 with valid_loss value: 3.1677212715148926.
Better model found at epoch 21 with valid_loss value: 3.116489887237549.
Better model found at epoch 22 with valid_loss value: 3.082704544067383.
Better model found at epoch 23 with valid_loss value: 3.028759479522705.
Better model found at epoch 24 with valid_loss value: 2.986736536026001.
Better model found at epoch 25 with valid_loss value: 2.973459482192993.
Better model found at epoch 26 with valid_loss value: 2.90836238861084.
Better model found at epoch 28 with valid_loss value: 2.8817169666290283.
Better model found at epoch 29 with valid_loss value: 2.8673057556152344.
Better model found at epoch 30 with valid_loss value: 2.821798086166382.
Better model found at epoch 31 with valid_loss value: 2.812800884246826.
Better model found at epoch 32 with valid_loss value: 2.7604925632476807.
Better model found at epoch 34 with valid_loss value: 2.7430169582366943.
Better model found at epoch 35 with valid_loss value: 2.7379424571990967.
Better model found at epoch 36 with valid_loss value: 2.702836275100708.
Better model found at epoch 37 with valid_loss value: 2.700305223464966.
Better model found at epoch 38 with valid_loss value: 2.698695659637451.
Better model found at epoch 39 with valid_loss value: 2.6850714683532715.
Better model found at epoch 40 with valid_loss value: 2.6834678649902344.
Better model found at epoch 41 with valid_loss value: 2.638960599899292.
Better model found at epoch 42 with valid_loss value: 2.627490997314453.
Better model found at epoch 43 with valid_loss value: 2.6076879501342773.
Better model found at epoch 44 with valid_loss value: 2.6004419326782227.
Better model found at epoch 46 with valid_loss value: 2.5910112857818604.
Better model found at epoch 47 with valid_loss value: 2.589611530303955.
Better model found at epoch 48 with valid_loss value: 2.5892884731292725.
Better model found at epoch 51 with valid_loss value: 2.578306198120117.
Better model found at epoch 52 with valid_loss value: 2.5655601024627686.
Better model found at epoch 54 with valid_loss value: 2.5531835556030273.
Better model found at epoch 60 with valid_loss value: 2.53802227973938.
Better model found at epoch 62 with valid_loss value: 2.528153419494629.
Better model found at epoch 69 with valid_loss value: 2.5226380825042725.
Better model found at epoch 73 with valid_loss value: 2.514587640762329.
Better model found at epoch 84 with valid_loss value: 2.5143048763275146.
Better model found at epoch 88 with valid_loss value: 2.513319492340088.
Better model found at epoch 89 with valid_loss value: 2.5111522674560547.

========================= cnn_lstm =========================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNRNN' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD0F1C5AD0>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.604450225830078.
Better model found at epoch 1 with valid_loss value: 4.602069854736328.
Better model found at epoch 2 with valid_loss value: 4.596027851104736.
Better model found at epoch 3 with valid_loss value: 4.582094192504883.
Better model found at epoch 4 with valid_loss value: 4.544991970062256.
Better model found at epoch 5 with valid_loss value: 4.462834358215332.
Better model found at epoch 6 with valid_loss value: 4.358616352081299.
Better model found at epoch 7 with valid_loss value: 4.239348888397217.
Better model found at epoch 8 with valid_loss value: 4.127914905548096.
Better model found at epoch 9 with valid_loss value: 4.00471830368042.
Better model found at epoch 10 with valid_loss value: 3.920595169067383.
Better model found at epoch 11 with valid_loss value: 3.7903690338134766.
Better model found at epoch 12 with valid_loss value: 3.7309625148773193.
Better model found at epoch 13 with valid_loss value: 3.6200244426727295.
Better model found at epoch 14 with valid_loss value: 3.535318374633789.
Better model found at epoch 15 with valid_loss value: 3.477121114730835.
Better model found at epoch 16 with valid_loss value: 3.396002769470215.
Better model found at epoch 17 with valid_loss value: 3.317375659942627.
Better model found at epoch 18 with valid_loss value: 3.286020040512085.
Better model found at epoch 19 with valid_loss value: 3.2069997787475586.
Better model found at epoch 20 with valid_loss value: 3.1642372608184814.
Better model found at epoch 21 with valid_loss value: 3.12743878364563.
Better model found at epoch 22 with valid_loss value: 3.0633771419525146.
Better model found at epoch 23 with valid_loss value: 3.048617124557495.
Better model found at epoch 24 with valid_loss value: 2.9898951053619385.
Better model found at epoch 26 with valid_loss value: 2.972452402114868.
Better model found at epoch 27 with valid_loss value: 2.929908275604248.
Better model found at epoch 28 with valid_loss value: 2.8835999965667725.
Better model found at epoch 29 with valid_loss value: 2.8670880794525146.
Better model found at epoch 31 with valid_loss value: 2.8035242557525635.
Better model found at epoch 32 with valid_loss value: 2.7975053787231445.
Better model found at epoch 33 with valid_loss value: 2.7951438426971436.
Better model found at epoch 35 with valid_loss value: 2.765923261642456.
Better model found at epoch 36 with valid_loss value: 2.7104501724243164.
Better model found at epoch 38 with valid_loss value: 2.7066826820373535.
Better model found at epoch 40 with valid_loss value: 2.678682804107666.
Better model found at epoch 41 with valid_loss value: 2.6634087562561035.
Better model found at epoch 43 with valid_loss value: 2.645742177963257.
Better model found at epoch 44 with valid_loss value: 2.6311371326446533.
Better model found at epoch 46 with valid_loss value: 2.599004030227661.
Better model found at epoch 49 with valid_loss value: 2.598144292831421.
Better model found at epoch 50 with valid_loss value: 2.59348464012146.
Better model found at epoch 51 with valid_loss value: 2.575437068939209.
Better model found at epoch 52 with valid_loss value: 2.568232536315918.
Better model found at epoch 53 with valid_loss value: 2.5448946952819824.
Better model found at epoch 55 with valid_loss value: 2.540693998336792.
Better model found at epoch 60 with valid_loss value: 2.5281474590301514.
Better model found at epoch 61 with valid_loss value: 2.5273776054382324.
Better model found at epoch 63 with valid_loss value: 2.507201910018921.
Better model found at epoch 67 with valid_loss value: 2.5030813217163086.
Better model found at epoch 71 with valid_loss value: 2.489387273788452.
Better model found at epoch 88 with valid_loss value: 2.485952377319336.
Better model found at epoch 96 with valid_loss value: 2.484299659729004.
Better model found at epoch 98 with valid_loss value: 2.481602907180786.

======================== bi_gru_seq ========================

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'BiGRUWithSeq' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000001FD11460B90>
cuda:0
cuda:0

Better model found at epoch 0 with valid_loss value: 4.607635498046875.
Better model found at epoch 1 with valid_loss value: 4.607481002807617.
Better model found at epoch 2 with valid_loss value: 4.607260704040527.
Better model found at epoch 3 with valid_loss value: 4.607045650482178.
Better model found at epoch 4 with valid_loss value: 4.60671329498291.
Better model found at epoch 5 with valid_loss value: 4.60589075088501.
Better model found at epoch 6 with valid_loss value: 4.601866245269775.
Better model found at epoch 7 with valid_loss value: 4.58761739730835.
Better model found at epoch 8 with valid_loss value: 4.579031467437744.
Better model found at epoch 9 with valid_loss value: 4.566543102264404.
Better model found at epoch 10 with valid_loss value: 4.56339693069458.
Better model found at epoch 11 with valid_loss value: 4.55875301361084.
Better model found at epoch 12 with valid_loss value: 4.553063869476318.
Better model found at epoch 13 with valid_loss value: 4.547448635101318.
Better model found at epoch 14 with valid_loss value: 4.544198989868164.
Better model found at epoch 15 with valid_loss value: 4.543849945068359.
Better model found at epoch 16 with valid_loss value: 4.538638114929199.
Better model found at epoch 17 with valid_loss value: 4.53376579284668.
Better model found at epoch 18 with valid_loss value: 4.528838634490967.
Better model found at epoch 19 with valid_loss value: 4.525669574737549.
Better model found at epoch 21 with valid_loss value: 4.517733573913574.
Better model found at epoch 22 with valid_loss value: 4.506872177124023.
Better model found at epoch 23 with valid_loss value: 4.495197296142578.
Better model found at epoch 24 with valid_loss value: 4.487104892730713.
Better model found at epoch 25 with valid_loss value: 4.47283935546875.
Better model found at epoch 26 with valid_loss value: 4.467813968658447.
Better model found at epoch 27 with valid_loss value: 4.464437961578369.
Better model found at epoch 28 with valid_loss value: 4.457888603210449.
Better model found at epoch 29 with valid_loss value: 4.445819854736328.
Better model found at epoch 30 with valid_loss value: 4.42752742767334.
Better model found at epoch 31 with valid_loss value: 4.426669120788574.
Better model found at epoch 32 with valid_loss value: 4.409695148468018.
Better model found at epoch 34 with valid_loss value: 4.401805400848389.
Better model found at epoch 35 with valid_loss value: 4.388584613800049.
Better model found at epoch 36 with valid_loss value: 4.380462646484375.
Better model found at epoch 37 with valid_loss value: 4.373281478881836.
Better model found at epoch 38 with valid_loss value: 4.365540504455566.
Better model found at epoch 40 with valid_loss value: 4.356991767883301.
Better model found at epoch 41 with valid_loss value: 4.34966516494751.
Better model found at epoch 42 with valid_loss value: 4.347183704376221.
Better model found at epoch 44 with valid_loss value: 4.337997913360596.
Better model found at epoch 45 with valid_loss value: 4.333572864532471.
Better model found at epoch 46 with valid_loss value: 4.3215436935424805.
Better model found at epoch 47 with valid_loss value: 4.321521282196045.
Better model found at epoch 48 with valid_loss value: 4.318062782287598.
Better model found at epoch 49 with valid_loss value: 4.316257953643799.
Better model found at epoch 50 with valid_loss value: 4.312010288238525.
Better model found at epoch 51 with valid_loss value: 4.302764415740967.
Better model found at epoch 52 with valid_loss value: 4.295382499694824.
Better model found at epoch 53 with valid_loss value: 4.289910793304443.
Better model found at epoch 54 with valid_loss value: 4.287582874298096.
Better model found at epoch 55 with valid_loss value: 4.286193370819092.
Better model found at epoch 56 with valid_loss value: 4.283693790435791.
Better model found at epoch 58 with valid_loss value: 4.282133102416992.
Better model found at epoch 59 with valid_loss value: 4.276700496673584.
Better model found at epoch 61 with valid_loss value: 4.267934322357178.
Better model found at epoch 63 with valid_loss value: 4.262537002563477.
Better model found at epoch 64 with valid_loss value: 4.253715991973877.
Better model found at epoch 66 with valid_loss value: 4.250931262969971.
Better model found at epoch 67 with valid_loss value: 4.23980712890625.
Better model found at epoch 68 with valid_loss value: 4.238269805908203.
Better model found at epoch 72 with valid_loss value: 4.236316680908203.
Better model found at epoch 73 with valid_loss value: 4.228473663330078.
Better model found at epoch 74 with valid_loss value: 4.227290153503418.
Better model found at epoch 76 with valid_loss value: 4.22568941116333.
Better model found at epoch 77 with valid_loss value: 4.220773220062256.
Better model found at epoch 80 with valid_loss value: 4.218595504760742.
Better model found at epoch 81 with valid_loss value: 4.2176690101623535.
Better model found at epoch 82 with valid_loss value: 4.217523097991943.
Better model found at epoch 83 with valid_loss value: 4.214816570281982.
Better model found at epoch 87 with valid_loss value: 4.214226245880127.
Better model found at epoch 88 with valid_loss value: 4.214042663574219.
Better model found at epoch 89 with valid_loss value: 4.211256504058838.
Better model found at epoch 95 with valid_loss value: 4.210718154907227.

The baseline model gave the highest accuracy of 48%

Validation

In [73]:
inf_fname = 'inference'
os.makedirs(inf_fname,exist_ok=True)

for model_name, i in inferences:
    i.to_csv(os.path.join(inf_fname, f'{model_name}.csv'), index=False)
    print(f"Saved inference for {model_name} to {os.path.join(inf_fname, f'{model_name}.csv')}")
    for ind in range(10):
        tp_fp_classification_report(i, ind)
    print()

Saved inference for gru_baseline to inference\gru_baseline.csv
================== Clf Report for AXE (0) ==================
True Positives: 2
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 1
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 2
False Positives: 1
================== Clf Report for BEE (3) ==================
True Positives: 1
False Positives: 10
================ Clf Report for BELIEVE (4) ================
True Positives: 1
False Positives: 0
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 2
================= Clf Report for BITE (6) ==================
True Positives: 0
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 2
False Positives: 3
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 2
================ Clf Report for BOTTLE (9) =================
True Positives: 0
False Positives: 1

Saved inference for lstm_baseline to inference\lstm_baseline.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 3
False Positives: 1
================== Clf Report for BEE (3) ==================
True Positives: 1
False Positives: 1
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 3
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 2
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 2
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 0

Saved inference for cnn_gru to inference\cnn_gru.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 1
============== Clf Report for BASKETBALL (2) ===============
True Positives: 1
False Positives: 3
================== Clf Report for BEE (3) ==================
True Positives: 0
False Positives: 1
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 1
================= Clf Report for BITE (6) ==================
True Positives: 0
False Positives: 1
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 3
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 2

Saved inference for cnn_lstm to inference\cnn_lstm.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 1
False Positives: 1
============== Clf Report for BASKETBALL (2) ===============
True Positives: 0
False Positives: 2
================== Clf Report for BEE (3) ==================
True Positives: 0
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 1
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 2
False Positives: 1
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 1

Saved inference for bi_gru_seq to inference\bi_gru_seq.csv
================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 0
False Positives: 0
============== Clf Report for BASKETBALL (2) ===============
True Positives: 3
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 0
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 0
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 2
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 0
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 0
False Positives: 3
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 0

In [17]:
from models import CNNBiGRU_diogo

cnn_kwargs = {
    'out_channels': 64,
    'kernel_size': 3,
    'dropout': 0.2,
    'use_pooling': False
}

rnn_kwargs = {
    'num_layers': 1,
    'bidirectional': True,
}

RNN_HIDDEN_SIZE = 256

INPUT_SIZE = 144
NUM_CLASSES = 100
EPOCHS = 100
BATCH_SIZE = 64
LR_MAX = 1e-3
VERBOSE = True

model_name = 'cnn_gru'
cnn_gru = CNNBiGRU_diogo(input_size=INPUT_SIZE, num_classes=NUM_CLASSES)
cnngru_no_pool_learner = create_fast_trainer(cnn_gru, train_ds, valid_ds, model_name, batch_size=BATCH_SIZE)
cnngru_no_pool_learner = train_model(cnngru_no_pool_learner, EPOCHS, lr_max=LR_MAX)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'CNNBiGRU_diogo' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x000002563EBA9490>
cuda:0
cuda:0
Found model cnn_gru in the models directory.

Better model found at epoch 0 with valid_loss value: 4.603675365447998.
Better model found at epoch 1 with valid_loss value: 4.602232933044434.
Better model found at epoch 2 with valid_loss value: 4.597667694091797.
Better model found at epoch 3 with valid_loss value: 4.590296268463135.
Better model found at epoch 4 with valid_loss value: 4.494667053222656.
Better model found at epoch 5 with valid_loss value: 4.243320465087891.
Better model found at epoch 6 with valid_loss value: 4.175131797790527.
Better model found at epoch 7 with valid_loss value: 4.093013763427734.
Better model found at epoch 8 with valid_loss value: 3.9779560565948486.
Better model found at epoch 9 with valid_loss value: 3.800820827484131.
Better model found at epoch 10 with valid_loss value: 3.577139377593994.
Better model found at epoch 11 with valid_loss value: 3.440542697906494.
Better model found at epoch 12 with valid_loss value: 3.424759864807129.
Better model found at epoch 13 with valid_loss value: 3.1773319244384766.
Better model found at epoch 14 with valid_loss value: 3.133458137512207.
Better model found at epoch 15 with valid_loss value: 2.9584529399871826.
Better model found at epoch 16 with valid_loss value: 2.8314831256866455.
Better model found at epoch 17 with valid_loss value: 2.714733123779297.
Better model found at epoch 18 with valid_loss value: 2.67168927192688.
Better model found at epoch 19 with valid_loss value: 2.618403434753418.
Better model found at epoch 20 with valid_loss value: 2.330489158630371.
Better model found at epoch 21 with valid_loss value: 2.232555389404297.
Better model found at epoch 23 with valid_loss value: 2.105555772781372.
Better model found at epoch 24 with valid_loss value: 1.927905797958374.
Better model found at epoch 26 with valid_loss value: 1.923455834388733.
Better model found at epoch 28 with valid_loss value: 1.7925970554351807.
Better model found at epoch 29 with valid_loss value: 1.754149317741394.
Better model found at epoch 33 with valid_loss value: 1.5901230573654175.
Better model found at epoch 40 with valid_loss value: 1.5620222091674805.
Better model found at epoch 49 with valid_loss value: 1.5402387380599976.
Better model found at epoch 54 with valid_loss value: 1.5098189115524292.

In [12]:
inf = get_predictions(cnngru_no_pool_learner, test_ds)
for ind in range(10):
    tp_fp_classification_report(inf, ind)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

================== Clf Report for AXE (0) ==================
True Positives: 2
False Positives: 1
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 2
============== Clf Report for BASKETBALL (2) ===============
True Positives: 2
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 2
False Positives: 0
================ Clf Report for BELIEVE (4) ================
True Positives: 1
False Positives: 0
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 0
================= Clf Report for BITE (6) ==================
True Positives: 2
False Positives: 1
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 2
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 1
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 1

In [16]:
(inf.correct.sum() / inf.shape[0] * 100).item()

68.13725490196079

In [18]:
from models import TemporalConvTransformer

RNN_HIDDEN_SIZE = 256
NUM_CLASSES = 100
EPOCHS = 100
BATCH_SIZE = 64
LR_MAX = 1e-4
VERBOSE = True

temporal_transformer = TemporalConvTransformer(
    input_dim=144,
    patch_size=4,
    num_patches=4,         # 16 frames / 4 patch size
    embed_dim=256*2,
    num_heads=4,
    num_layers=2,
    num_classes=NUM_CLASSES,
    dropout=0.25
)

In [19]:
model_name = 'temporal_transformer'
tt_learner = create_fast_trainer(
    temporal_transformer,  # model
    train_ds=train_ds,
    valid_ds=valid_ds,
    model_name=model_name,
    batch_size=BATCH_SIZE,
    verbose=VERBOSE
)
tt_learner = train_model(tt_learner, EPOCHS, lr_max=LR_MAX)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

Error in summary: Exception occured in `TensorBoardCallback` when calling event `after_batch`:
	'TemporalConvTransformer' object has no attribute 'smooth_loss'
cuda:0
torch.float32
<fastai.optimizer.Optimizer object at 0x00000273958DD490>
cuda:0
cuda:0
Found model temporal_transformer in the models directory.

Better model found at epoch 0 with valid_loss value: 4.63035774230957.
Better model found at epoch 1 with valid_loss value: 4.61361026763916.
Better model found at epoch 2 with valid_loss value: 4.605236530303955.
Better model found at epoch 3 with valid_loss value: 4.60016393661499.
Better model found at epoch 4 with valid_loss value: 4.592502593994141.
Better model found at epoch 5 with valid_loss value: 4.584184169769287.
Better model found at epoch 6 with valid_loss value: 4.564104080200195.
Better model found at epoch 7 with valid_loss value: 4.507229804992676.
Better model found at epoch 8 with valid_loss value: 4.330585956573486.
Better model found at epoch 9 with valid_loss value: 4.174994945526123.
Better model found at epoch 10 with valid_loss value: 4.113237380981445.
Better model found at epoch 11 with valid_loss value: 4.033470153808594.
Better model found at epoch 12 with valid_loss value: 3.9061779975891113.
Better model found at epoch 13 with valid_loss value: 3.867990493774414.
Better model found at epoch 14 with valid_loss value: 3.7764153480529785.
Better model found at epoch 15 with valid_loss value: 3.6788456439971924.
Better model found at epoch 16 with valid_loss value: 3.5846245288848877.
Better model found at epoch 17 with valid_loss value: 3.4461352825164795.
Better model found at epoch 18 with valid_loss value: 3.3986990451812744.
Better model found at epoch 19 with valid_loss value: 3.2802584171295166.
Better model found at epoch 20 with valid_loss value: 3.182896614074707.
Better model found at epoch 21 with valid_loss value: 3.1572980880737305.
Better model found at epoch 23 with valid_loss value: 3.044898509979248.
Better model found at epoch 24 with valid_loss value: 2.914581060409546.
Better model found at epoch 26 with valid_loss value: 2.828751564025879.
Better model found at epoch 27 with valid_loss value: 2.734994411468506.
Better model found at epoch 28 with valid_loss value: 2.7134079933166504.
Better model found at epoch 29 with valid_loss value: 2.683351516723633.
Better model found at epoch 30 with valid_loss value: 2.5622992515563965.
Better model found at epoch 31 with valid_loss value: 2.524360179901123.
Better model found at epoch 32 with valid_loss value: 2.397573232650757.
Better model found at epoch 34 with valid_loss value: 2.3141911029815674.
Better model found at epoch 35 with valid_loss value: 2.2683560848236084.
Better model found at epoch 37 with valid_loss value: 2.247546434402466.
Better model found at epoch 39 with valid_loss value: 2.2282605171203613.
Better model found at epoch 40 with valid_loss value: 2.11476469039917.
Better model found at epoch 41 with valid_loss value: 2.0452115535736084.
Better model found at epoch 43 with valid_loss value: 2.0250532627105713.
Better model found at epoch 44 with valid_loss value: 2.010485887527466.
Better model found at epoch 45 with valid_loss value: 1.9266277551651.
Better model found at epoch 46 with valid_loss value: 1.9053760766983032.
Better model found at epoch 48 with valid_loss value: 1.8622294664382935.
Better model found at epoch 50 with valid_loss value: 1.8250951766967773.
Better model found at epoch 51 with valid_loss value: 1.8051034212112427.
Better model found at epoch 53 with valid_loss value: 1.773878812789917.
Better model found at epoch 55 with valid_loss value: 1.7697337865829468.
Better model found at epoch 56 with valid_loss value: 1.734560251235962.
Better model found at epoch 61 with valid_loss value: 1.708884596824646.
Better model found at epoch 62 with valid_loss value: 1.6975098848342896.
Better model found at epoch 63 with valid_loss value: 1.6666375398635864.
Better model found at epoch 67 with valid_loss value: 1.6552627086639404.
Better model found at epoch 68 with valid_loss value: 1.6536206007003784.
Better model found at epoch 69 with valid_loss value: 1.6447781324386597.
Better model found at epoch 72 with valid_loss value: 1.6242876052856445.
Better model found at epoch 75 with valid_loss value: 1.6204251050949097.
Better model found at epoch 77 with valid_loss value: 1.614997148513794.

In [21]:
inf = get_predictions(tt_learner, test_ds)
for ind in range(10):
    tp_fp_classification_report(inf, ind)

c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()
c:\Users\jaabi\Documents\ulisboa\deep learning\asl_project\venv\Lib\site-packages\fastai\callback\fp16.py:47: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.autocast,self.learn.scaler,self.scales = autocast(dtype=dtype),GradScaler(**self.kwargs),L()

================== Clf Report for AXE (0) ==================
True Positives: 1
False Positives: 0
=============== Clf Report for BACKPACK (1) ================
True Positives: 2
False Positives: 1
============== Clf Report for BASKETBALL (2) ===============
True Positives: 1
False Positives: 0
================== Clf Report for BEE (3) ==================
True Positives: 1
False Positives: 1
================ Clf Report for BELIEVE (4) ================
True Positives: 1
False Positives: 1
================= Clf Report for BELT (5) ==================
True Positives: 3
False Positives: 2
================= Clf Report for BITE (6) ==================
True Positives: 1
False Positives: 0
================= Clf Report for BLOOD (7) =================
True Positives: 1
False Positives: 1
================ Clf Report for BORROW (8) =================
True Positives: 1
False Positives: 0
================ Clf Report for BOTTLE (9) =================
True Positives: 1
False Positives: 1